/*
Copyright 2026 The Railgrid Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package install holds the one-shot bootstrap a railgrid provider runs against
// its own kcp workspace, using the workspace-admin kubeconfig the platform
// admin onboarded (which already points at root:railgrid:providers:<name>).
//
// It is the provider-side half of the bootstrap split: the admin UI/API creates
// the provider workspace + ServiceAccount + legacy-token kubeconfig, and the
// provider's `init` (driven by this package) applies everything that lives
// INSIDE the workspace — APIResourceSchemas, the APIExport, the
// APIExportEndpointSlice the multicluster manager watches, and the bind RBAC
// grant that lets tenants APIBind. The hub no longer provisions any of this.
//
// A provider declares exactly two objects and this package applies them
// verbatim: the CatalogEntry (manifest.yaml, hand-written) and the APIExport
// (config/kcp/apiexport-<name>.yaml, generated by
// provider-sdk/cmd/apiexportgen from that manifest plus kcp apigen). Both, with
// the APIResourceSchemas, travel in the chart's files/ directory, which the
// image bakes at /etc/railgrid/kcp and init reads through Options.KCPDir.
// Nothing about the export is assembled in Go: what a reviewer reads in the
// diff is what lands in the workspace.
//
// Every step is idempotent. The logic is ported from the former hub
// provisioner (pkg/hub/providers/provision.go) so the resulting objects are
// byte-for-byte compatible with what the hub used to create — with one
// deliberate change: identityHash for first-party permission claims is supplied
// by the caller (a Helm value the admin copies from the /bonkers root-identities
// view) instead of being resolved from the parent workspace, which this
// workspace-scoped kubeconfig cannot read. See Options.IdentityHashes.
package install

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/yaml"
)

var (
	apiResourceSchemaGVR = schema.GroupVersionResource{
		Group: "apis.kcp.io", Version: "v1alpha1", Resource: "apiresourceschemas",
	}
	// APIExport is v1alpha2 (matches the hub provisioner and Enable flow).
	apiExportGVR = schema.GroupVersionResource{
		Group: "apis.kcp.io", Version: "v1alpha2", Resource: "apiexports",
	}
	apiExportEndpointSliceGVR = schema.GroupVersionResource{
		Group: "apis.kcp.io", Version: "v1alpha1", Resource: "apiexportendpointslices",
	}
	clusterRoleGVR = schema.GroupVersionResource{
		Group: "rbac.authorization.k8s.io", Version: "v1", Resource: "clusterroles",
	}
	clusterRoleBindingGVR = schema.GroupVersionResource{
		Group: "rbac.authorization.k8s.io", Version: "v1", Resource: "clusterrolebindings",
	}
)

// Options bundles everything a provider's init needs.
type Options struct {
	// Config is the workspace-admin rest.Config (its Host already targets the
	// provider workspace cluster, e.g. .../clusters/root:railgrid:providers:code).
	Config *rest.Config
	// ExportName is the provider's APIExport name (also the slice name by
	// convention), e.g. "code.providers.railgrid.ai".
	ExportName string
	// WorkspacePath is the logical-cluster path the APIExport lives in, e.g.
	// "root:railgrid:providers:code".
	//
	// OPTIONAL, and normally best left empty: empty means "the workspace Config
	// targets", which is where the endpoint slice and the export both live. It
	// is resolved at install time from that workspace's LogicalCluster and
	// written to the slice explicitly (see EnsureAPIExportEndpointSlice).
	//
	// Leaving it empty is what makes a provider chart workspace-agnostic: the
	// same chart bootstraps correctly whether its kubeconfig points at
	// root:railgrid:providers/<name> or at an org's own
	// root:railgrid:tenants/<org>/providers/<name>. Hardcoding a platform path
	// here instead would publish endpoints for an export that does not exist at
	// that path when the provider is self-hosted by an organization.
	//
	// Set it only to reference an export in a DIFFERENT workspace than the one
	// Config targets.
	WorkspacePath string
	// KCPDir is the directory holding the two declarative objects a provider
	// ships, exactly as codegen wrote them:
	//
	//   apiexport.yaml   the generated APIExport (name + permission claims
	//                    from manifest.yaml, resources from kcp apigen)
	//   *.yaml           the APIResourceSchemas, either directly in KCPDir
	//                    (apiresourceschema-<resource>.<group>.yaml, as
	//                    config/kcp/ names them) or in a schemas/
	//                    subdirectory (the chart's flat
	//                    <resource>.<group>.yaml names)
	//
	// The chart's deploy/chart/files/ IS this directory: it is baked into the
	// image at /etc/railgrid/kcp and pointed at by RAILGRID_KCP_DIR. Required.
	KCPDir string

	// IdentityHashes supplies the APIExport identityHash for first-party
	// (*.railgrid.ai) permission-claim groups, keyed by API group.
	//
	// kcp rejects a permissionClaim on a non-built-in type unless it carries
	// the identityHash of the APIExport that serves it — and that hash is a
	// property of the INSTALLATION, not of the provider: the same claim points
	// at a different export in the platform deployment and in an org's
	// self-hosted copy. So it cannot live in the generated file, and the
	// platform admin supplies it instead (the /bonkers root-identities view →
	// a Helm value → RAILGRID_IDENTITY_HASHES). Bootstrap stamps it onto every
	// matching claim and FAILS when one is missing, rather than applying an
	// export kcp will reject with a message about an unrelated field.
	//
	// Built-in types (empty group, or any non-railgrid group) need no hash.
	IdentityHashes map[string]string

	// CatalogEntryFile, when set, is the path to a CatalogEntry YAML the
	// provider self-registers into its OWN workspace (which the platform's
	// Provider controller bound to providers.railgrid.ai). Empty → skip
	// (e.g. providers whose CatalogEntry is applied to root:railgrid:providers by
	// an admin instead). Applied last, after the APIExport exists.
	CatalogEntryFile string
}

// Bootstrap runs the full provider workspace bootstrap idempotently:
// schemas → APIExport → APIExportEndpointSlice → bind grant. Safe to re-run.
func Bootstrap(ctx context.Context, opts Options) error {
	if opts.Config == nil {
		return fmt.Errorf("install: Config is required")
	}
	if opts.ExportName == "" {
		return fmt.Errorf("install: ExportName is required")
	}
	cl, err := dynamic.NewForConfig(opts.Config)
	if err != nil {
		return fmt.Errorf("install: dynamic client: %w", err)
	}

	if opts.KCPDir == "" {
		return fmt.Errorf("install: KCPDir is required")
	}
	export, err := LoadAPIExport(filepath.Join(opts.KCPDir, APIExportFileName))
	if err != nil {
		return fmt.Errorf("install: %w", err)
	}
	// The export the provider ships and the export the rest of init wires up
	// (endpoint slice, bind grant) must be the same object. They are written
	// down in two places — manifest.yaml, which generates the file, and the
	// provider's own apiExportName constant — so check rather than assume: a
	// mismatch would otherwise surface as a slice for an export that does not
	// exist, which kcp reports as a bind-permission error.
	if name := export.GetName(); name != opts.ExportName {
		return fmt.Errorf("install: %s declares APIExport %q but init was configured for %q; re-run codegen", filepath.Join(opts.KCPDir, APIExportFileName), name, opts.ExportName)
	}
	if err := ApplySchemasFromDir(ctx, cl, opts.KCPDir); err != nil {
		return fmt.Errorf("install: apply schemas: %w", err)
	}
	if err := StampIdentityHashes(export, opts.IdentityHashes); err != nil {
		return fmt.Errorf("install: %w", err)
	}
	if err := ApplyAPIExport(ctx, cl, export); err != nil {
		return fmt.Errorf("install: apply APIExport: %w", err)
	}
	if err := EnsureAPIExportEndpointSlice(ctx, cl, opts.ExportName, opts.ExportName, opts.WorkspacePath); err != nil {
		return fmt.Errorf("install: ensure APIExportEndpointSlice: %w", err)
	}
	if err := ApplyBindGrant(ctx, cl, opts.ExportName); err != nil {
		return fmt.Errorf("install: apply bind grant: %w", err)
	}
	if opts.CatalogEntryFile != "" {
		if err := ApplyCatalogEntry(ctx, cl, opts.CatalogEntryFile); err != nil {
			return fmt.Errorf("install: apply CatalogEntry: %w", err)
		}
	}
	return nil
}

// catalogEntryGVR is the cluster-scoped CatalogEntry served by the
// providers.railgrid.ai APIExport, which the platform's Provider controller
// binds into each provider sub-workspace.
var catalogEntryGVR = schema.GroupVersionResource{
	Group: "providers.railgrid.ai", Version: "v1alpha1", Resource: "catalogentries",
}

// ApplyCatalogEntry reads a CatalogEntry YAML from path and create-or-updates it
// in the workspace cl targets (the provider's own sub-workspace). This is how a
// provider self-registers its catalog entry from inside its workspace, rather
// than an admin applying it to root:railgrid:providers. Idempotent.
func ApplyCatalogEntry(ctx context.Context, cl dynamic.Interface, path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading CatalogEntry file %s: %w", path, err)
	}
	u := &unstructured.Unstructured{}
	if err := yaml.Unmarshal(raw, &u.Object); err != nil {
		return fmt.Errorf("parsing CatalogEntry file %s: %w", path, err)
	}
	if u.GetAPIVersion() != "providers.railgrid.ai/v1alpha1" || u.GetKind() != "CatalogEntry" {
		return fmt.Errorf("file %s: expected CatalogEntry providers.railgrid.ai/v1alpha1, got %s/%s", path, u.GetAPIVersion(), u.GetKind())
	}
	if u.GetName() == "" {
		return fmt.Errorf("file %s: metadata.name is required", path)
	}
	return applyUnstructured(ctx, cl, catalogEntryGVR, u)
}

// APIExportFileName is the generated APIExport inside KCPDir. One fixed name,
// because the file is an output: the provider's codegen writes it and init
// applies it verbatim.
const APIExportFileName = "apiexport.yaml"

// schemaFiles returns the APIResourceSchema files in a KCPDir, sorted for
// determinism. Two layouts are accepted, because two directories in the tree
// legitimately hold schemas:
//
//   - config/kcp/, where apigen writes apiresourceschema-<resource>.<group>.yaml
//     next to the generated apiexport;
//   - the chart's files/, where the schemas sit in a schemas/ subdirectory
//     under their flat <resource>.<group>.yaml names, beside apiexport.yaml.
//
// Anything named apiexport* is the export, not a schema, and is skipped.
func schemaFiles(dir string) ([]string, error) {
	var files []string
	collect := func(from string, required bool) error {
		entries, err := os.ReadDir(from)
		if err != nil {
			if os.IsNotExist(err) && !required {
				return nil
			}
			return fmt.Errorf("reading %s: %w", from, err)
		}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if !strings.HasSuffix(name, ".yaml") && !strings.HasSuffix(name, ".yml") {
				continue
			}
			if strings.HasPrefix(name, "apiexport") {
				continue
			}
			files = append(files, filepath.Join(from, name))
		}
		return nil
	}
	if err := collect(dir, true); err != nil {
		return nil, err
	}
	if err := collect(filepath.Join(dir, "schemas"), false); err != nil {
		return nil, err
	}
	sort.Strings(files)
	return files, nil
}

// ApplySchemasFromDir applies every APIResourceSchema in a KCPDir, in sorted
// order for determinism. APIResourceSchemas are immutable in kcp, so
// re-applying the same name is a no-op (AlreadyExists tolerated); a body change
// must come with a new version-prefixed name, which hack/apigen.sh mints.
func ApplySchemasFromDir(ctx context.Context, cl dynamic.Interface, dir string) error {
	files, err := schemaFiles(dir)
	if err != nil {
		return err
	}
	for _, path := range files {
		u, err := readSchema(path)
		if err != nil {
			return err
		}
		if _, err := cl.Resource(apiResourceSchemaGVR).Create(ctx, u, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
			return fmt.Errorf("creating schema %s: %w", u.GetName(), err)
		}
	}
	return nil
}

func readSchema(path string) (*unstructured.Unstructured, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading schema file %s: %w", path, err)
	}
	u := &unstructured.Unstructured{}
	if err := yaml.Unmarshal(raw, &u.Object); err != nil {
		return nil, fmt.Errorf("parsing schema file %s: %w", path, err)
	}
	if u.GetAPIVersion() != "apis.kcp.io/v1alpha1" || u.GetKind() != "APIResourceSchema" {
		return nil, fmt.Errorf("schema file %s: expected APIResourceSchema apis.kcp.io/v1alpha1, got %s/%s", path, u.GetAPIVersion(), u.GetKind())
	}
	if u.GetName() == "" {
		return nil, fmt.Errorf("schema file %s: metadata.name is required", path)
	}
	return u, nil
}

// LoadAPIExport reads the generated APIExport from path. The file is written by
// provider-sdk/cmd/apiexportgen out of manifest.yaml (name + permission claims)
// and kcp apigen (resources), so init applies a declaration a reviewer can read
// in the diff rather than one assembled from Go literals at runtime.
func LoadAPIExport(path string) (*unstructured.Unstructured, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading APIExport file %s: %w", path, err)
	}
	u := &unstructured.Unstructured{}
	if err := yaml.Unmarshal(raw, &u.Object); err != nil {
		return nil, fmt.Errorf("parsing APIExport file %s: %w", path, err)
	}
	if u.GetAPIVersion() != "apis.kcp.io/v1alpha2" || u.GetKind() != "APIExport" {
		return nil, fmt.Errorf("APIExport file %s: expected APIExport apis.kcp.io/v1alpha2, got %s/%s", path, u.GetAPIVersion(), u.GetKind())
	}
	if u.GetName() == "" {
		return nil, fmt.Errorf("APIExport file %s: metadata.name is required", path)
	}
	return u, nil
}

// firstPartyGroupSuffix marks the API groups railgrid itself serves. A claim on
// one of those is a claim on another APIExport's types, which kcp will only
// honor when the claim pins that export's identity.
const firstPartyGroupSuffix = ".railgrid.ai"

// IsFirstPartyGroup reports whether an API group is served by a railgrid
// APIExport (and therefore needs an identityHash on any claim against it).
func IsFirstPartyGroup(group string) bool {
	return group == "railgrid.ai" || strings.HasSuffix(group, firstPartyGroupSuffix)
}

// StampIdentityHashes writes the per-installation identityHash onto every
// first-party permission claim on export, and fails when one is missing.
//
// Failing here is the point. kcp does not reject an unpinned claim with
// "identityHash required"; it accepts the export and then quietly refuses the
// claim at bind time, so the provider comes up, reconciles nothing in tenant
// workspaces, and the only symptom is an informer that cannot find a kind.
func StampIdentityHashes(export *unstructured.Unstructured, hashes map[string]string) error {
	claims, found, err := unstructured.NestedSlice(export.Object, "spec", "permissionClaims")
	if err != nil {
		return fmt.Errorf("reading spec.permissionClaims on APIExport %s: %w", export.GetName(), err)
	}
	if !found || len(claims) == 0 {
		return nil
	}
	for _, claim := range claims {
		entry, ok := claim.(map[string]any)
		if !ok {
			return fmt.Errorf("APIExport %s: spec.permissionClaims entry is not a mapping", export.GetName())
		}
		group, _ := entry["group"].(string)
		if !IsFirstPartyGroup(group) {
			continue
		}
		hash := hashes[group]
		if hash == "" {
			resource, _ := entry["resource"].(string)
			return fmt.Errorf("APIExport %s claims %s.%s but no identityHash was supplied for group %s (set RAILGRID_IDENTITY_HASHES / the chart's identityHashes value from the admin root-identities view)", export.GetName(), resource, group, group)
		}
		entry["identityHash"] = hash
	}
	if err := unstructured.SetNestedSlice(export.Object, claims, "spec", "permissionClaims"); err != nil {
		return fmt.Errorf("writing spec.permissionClaims on APIExport %s: %w", export.GetName(), err)
	}
	return nil
}

// ParseIdentityHashes reads a "group=hash,group=hash" list, the form every
// provider's init takes from RAILGRID_IDENTITY_HASHES. Empty yields no hashes,
// which is correct for every in-tree provider today: none claims a first-party
// group, deliberately (one export can pin only one identity per resource for
// every consumer at once, which breaks as soon as one org self-hosts a
// dependency).
func ParseIdentityHashes(spec string) (map[string]string, error) {
	hashes := map[string]string{}
	for _, pair := range strings.Split(spec, ",") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		group, hash, ok := strings.Cut(pair, "=")
		group, hash = strings.TrimSpace(group), strings.TrimSpace(hash)
		if !ok || group == "" || hash == "" {
			return nil, fmt.Errorf("identity hashes: %q is not group=hash", pair)
		}
		hashes[group] = hash
	}
	return hashes, nil
}

// ApplyAPIExport applies the provider's generated APIExport: the object read
// from KCPDir/apiexport.yaml, with identityHashes already stamped. Nothing
// about it is assembled here — the name, the claims and the resources are all
// decided at codegen time and reviewed in the diff.
//
// Before applying, every APIResourceSchema the export references must exist in
// the workspace. A missing one means the chart's apiexport.yaml is newer than
// its schemas (a partial codegen, or a half-built image); kcp would accept the
// export and then serve a kind with no schema behind it.
//
// Merge, don't clobber: spec.resources has multiple writers (this init step,
// plus any runtime controller that mints per-object entries, e.g. the
// infrastructure templates virtual storage). Entries in the API groups this
// step owns are fully reconciled — upserted, and stale ones (renamed/removed
// resources) pruned. Entries in other groups are preserved untouched.
func ApplyAPIExport(ctx context.Context, cl dynamic.Interface, export *unstructured.Unstructured) error {
	exportName := export.GetName()
	if exportName == "" {
		return fmt.Errorf("APIExport has no metadata.name")
	}
	resources, _, err := unstructured.NestedSlice(export.Object, "spec", "resources")
	if err != nil {
		return fmt.Errorf("reading spec.resources on APIExport %s: %w", exportName, err)
	}
	for _, resource := range resources {
		entry, ok := resource.(map[string]any)
		if !ok {
			return fmt.Errorf("APIExport %s: spec.resources entry is not a mapping", exportName)
		}
		name, _ := entry["schema"].(string)
		if name == "" {
			continue // a virtual-storage entry references no APIResourceSchema
		}
		if err := waitForResourceExists(ctx, cl, apiResourceSchemaGVR, name); err != nil {
			return fmt.Errorf("APIExport %s references APIResourceSchema %s, which is not in this workspace: %w", exportName, name, err)
		}
	}

	desired := export.DeepCopy()
	desired.SetResourceVersion("")

	existing, err := cl.Resource(apiExportGVR).Get(ctx, exportName, metav1.GetOptions{})
	if apierrors.IsNotFound(err) {
		if _, err = cl.Resource(apiExportGVR).Create(ctx, desired, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
			return fmt.Errorf("creating APIExport %s: %w", exportName, err)
		}
		// Read-after-write: when the provider workspace is still being
		// (re)provisioned, the Create can report success without the object
		// durably landing (the write races the workspace bootstrap). Poll until
		// the export is observable so a lost write fails LOUDLY here — where the
		// init retries — instead of surfacing later as the misleading
		// "no permission to bind to export" from APIExportEndpointSlice admission,
		// which reports a *missing* export as a bind-permission error.
		if err := waitForResourceExists(ctx, cl, apiExportGVR, exportName); err != nil {
			return fmt.Errorf("APIExport %s not observable after create (workspace may still be provisioning): %w", exportName, err)
		}
		return nil
	}
	if err != nil {
		return fmt.Errorf("getting existing APIExport %s: %w", exportName, err)
	}

	existingResources, _, err := unstructured.NestedSlice(existing.Object, "spec", "resources")
	if err != nil {
		return fmt.Errorf("reading existing spec.resources on APIExport %s: %w", exportName, err)
	}
	if err := unstructured.SetNestedSlice(desired.Object, mergeAPIExportResources(existingResources, resources), "spec", "resources"); err != nil {
		return fmt.Errorf("merging spec.resources for APIExport %s: %w", exportName, err)
	}
	desired.SetResourceVersion(existing.GetResourceVersion())
	if _, err := cl.Resource(apiExportGVR).Update(ctx, desired, metav1.UpdateOptions{}); err != nil {
		return fmt.Errorf("updating APIExport %s: %w", exportName, err)
	}
	return nil
}

// waitForResourceExists polls until a cluster-scoped resource is observable via
// Get, or the deadline passes. It guards create-then-vanish races: when a
// provider workspace is being (re)provisioned concurrently, a Create can return
// success without the object durably landing. Returns nil once the object is
// readable, or the last error / a timeout otherwise.
func waitForResourceExists(ctx context.Context, cl dynamic.Interface, gvr schema.GroupVersionResource, name string) error {
	return wait.PollUntilContextTimeout(ctx, 500*time.Millisecond, 15*time.Second, true, func(ctx context.Context) (bool, error) {
		if _, err := cl.Resource(gvr).Get(ctx, name, metav1.GetOptions{}); err != nil {
			if apierrors.IsNotFound(err) {
				return false, nil
			}
			return false, err
		}
		return true, nil
	})
}

// EnsureAPIExportEndpointSlice ensures an APIExportEndpointSlice referencing the
// provider's APIExport exists in the workspace cl targets.
//
// workspacePath is the canonical path of the workspace the APIExport lives in.
// Empty means "the workspace cl targets": the path is resolved from that
// workspace's LogicalCluster, so callers stay workspace-agnostic (platform and
// org-hosted providers alike), and it is always written to spec.export.path.
//
// The slice must never be path-less. kcp does resolve an unset path to the
// slice's own logical cluster when serving, but each shard's endpoint-URL
// publisher finds the slices affected by an APIBinding through the binding's
// export reference, which is a canonical path; a path-less slice is indexed only
// under its logical-cluster name, so the lookup misses it. The first binding of
// the export on a shard other than the export's own then never makes that shard
// publish its virtual-workspace URL, and the provider silently reconciles
// nothing in tenant workspaces there until something else touches the slice.
// kcp versions that resolve the export in that lookup are not affected; writing
// the path keeps every version working.
//
// spec.export is immutable, so a pre-existing slice with a different path —
// including a path-less one written by an older SDK — is deleted and recreated.
// That happens once per slice; recreation makes every shard re-evaluate it, and
// the multicluster provider re-engages its endpoints when the slice reappears.
func EnsureAPIExportEndpointSlice(ctx context.Context, cl dynamic.Interface, sliceName, exportName, workspacePath string) error {
	if workspacePath == "" {
		resolved, err := workspacePathOf(ctx, cl)
		if err != nil {
			return fmt.Errorf("resolving workspace path for APIExportEndpointSlice %s: %w", sliceName, err)
		}
		workspacePath = resolved
	}
	want := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "apis.kcp.io/v1alpha1",
		"kind":       "APIExportEndpointSlice",
		"metadata":   map[string]any{"name": sliceName},
		"spec": map[string]any{"export": map[string]any{
			"name": exportName,
			"path": workspacePath,
		}},
	}}

	existing, err := cl.Resource(apiExportEndpointSliceGVR).Get(ctx, sliceName, metav1.GetOptions{})
	if apierrors.IsNotFound(err) {
		if _, err = cl.Resource(apiExportEndpointSliceGVR).Create(ctx, want, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
			return fmt.Errorf("creating APIExportEndpointSlice %s: %w", sliceName, err)
		}
		return nil
	}
	if err != nil {
		return fmt.Errorf("getting APIExportEndpointSlice %s: %w", sliceName, err)
	}
	existingPath, _, _ := unstructured.NestedString(existing.Object, "spec", "export", "path")
	if existingPath == workspacePath {
		return nil
	}
	if err := cl.Resource(apiExportEndpointSliceGVR).Delete(ctx, sliceName, metav1.DeleteOptions{}); err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("deleting stale APIExportEndpointSlice %s: %w", sliceName, err)
	}
	if _, err = cl.Resource(apiExportEndpointSliceGVR).Create(ctx, want, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
		return fmt.Errorf("recreating APIExportEndpointSlice %s: %w", sliceName, err)
	}
	return nil
}

// orgProviderWorkspacePrefix marks a provider workspace owned by one
// organization rather than the platform:
// root:railgrid:tenants:<orgUUID>:providers:<name>.
const orgProviderWorkspacePrefix = "root:railgrid:tenants:"

// isOrgOwnedWorkspace reports whether a workspace path belongs to a single
// organization. Matching on the separator matters: a sibling of the tenants
// container whose name merely starts with the same letters is not a tenant.
func isOrgOwnedWorkspace(path string) bool {
	return strings.HasPrefix(path, orgProviderWorkspacePrefix)
}

// ApplyBindGrant creates / updates the ClusterRole + ClusterRoleBinding in the
// provider workspace that lets any authenticated railgrid user bind to the
// provider's APIExport from their own workspace. Without it, kcp refuses
// tenant-side APIBinding creates with 403. Subject is "system:authenticated":
// the platform admin is the gatekeeper at onboard/install time.
//
// That gatekeeper argument does not carry over to an org-owned provider. Nobody
// vets those — an organization registers one itself — so granting bind to every
// authenticated user means a member of ANY organization who learns another
// org's UUID can hand-craft an APIBinding in their own workspace and consume a
// provider they were never offered. So for an org-owned workspace the grant is
// not created, and one left by an earlier install is removed.
//
// Nothing supported breaks: every APIBinding railgrid creates comes from the hub's
// Enable path, which runs as kcp-admin and needs no grant. What stops working
// is hand-writing an APIBinding with kubectl, which for an Org workspace is
// already outside the hub-mediated model (decision O-10).
func ApplyBindGrant(ctx context.Context, cl dynamic.Interface, exportName string) error {
	roleName := "railgrid:providers:bind:" + exportName

	// Resolve from the LogicalCluster rather than a caller-supplied path:
	// Options.WorkspacePath is deliberately empty in normal use, so that a
	// provider chart is workspace-agnostic. This client is already scoped to
	// the workspace being installed into, so it can just ask.
	path, err := workspacePathOf(ctx, cl)
	if err != nil {
		// Fail closed. An unresolvable path must not default to the widest
		// grant, and skipping costs only the unsupported kubectl path.
		return fmt.Errorf("resolving workspace path for bind grant of %s: %w", exportName, err)
	}
	if isOrgOwnedWorkspace(path) {
		return removeBindGrant(ctx, cl, roleName)
	}
	cr := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRole",
		"metadata":   map[string]any{"name": roleName},
		"rules": []any{
			map[string]any{
				"apiGroups":     []any{"apis.kcp.io"},
				"resources":     []any{"apiexports"},
				"verbs":         []any{"bind"},
				"resourceNames": []any{exportName},
			},
		},
	}}
	if err := applyUnstructured(ctx, cl, clusterRoleGVR, cr); err != nil {
		return fmt.Errorf("applying ClusterRole %s: %w", roleName, err)
	}
	crb := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRoleBinding",
		"metadata":   map[string]any{"name": roleName},
		"roleRef": map[string]any{
			"apiGroup": "rbac.authorization.k8s.io",
			"kind":     "ClusterRole",
			"name":     roleName,
		},
		"subjects": []any{
			map[string]any{
				"apiGroup": "rbac.authorization.k8s.io",
				"kind":     "Group",
				"name":     "system:authenticated",
			},
		},
	}}
	if err := applyUnstructured(ctx, cl, clusterRoleBindingGVR, crb); err != nil {
		return fmt.Errorf("applying ClusterRoleBinding %s: %w", roleName, err)
	}
	return nil
}

// logicalClusterGVR is kcp's per-workspace singleton, named "cluster", whose
// kcp.io/path annotation is the workspace's canonical path.
var logicalClusterGVR = schema.GroupVersionResource{
	Group: "core.kcp.io", Version: "v1alpha1", Resource: "logicalclusters",
}

// workspacePathOf returns the canonical path of the workspace cl is scoped to.
func workspacePathOf(ctx context.Context, cl dynamic.Interface) (string, error) {
	lc, err := cl.Resource(logicalClusterGVR).Get(ctx, "cluster", metav1.GetOptions{})
	if err != nil {
		return "", fmt.Errorf("getting LogicalCluster: %w", err)
	}
	path := lc.GetAnnotations()["kcp.io/path"]
	if path == "" {
		return "", fmt.Errorf("LogicalCluster carries no kcp.io/path annotation")
	}
	return path, nil
}

// removeBindGrant deletes a bind grant a previous install created, so that
// upgrading an org-owned provider closes the hole rather than leaving it open
// until someone notices. NotFound is success — the usual case.
func removeBindGrant(ctx context.Context, cl dynamic.Interface, roleName string) error {
	if err := cl.Resource(clusterRoleBindingGVR).Delete(ctx, roleName, metav1.DeleteOptions{}); err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("removing bind ClusterRoleBinding %s: %w", roleName, err)
	}
	if err := cl.Resource(clusterRoleGVR).Delete(ctx, roleName, metav1.DeleteOptions{}); err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("removing bind ClusterRole %s: %w", roleName, err)
	}
	return nil
}

// applyUnstructured is a create-or-update helper for cluster-scoped resources.
func applyUnstructured(ctx context.Context, cl dynamic.Interface, gvr schema.GroupVersionResource, desired *unstructured.Unstructured) error {
	existing, err := cl.Resource(gvr).Get(ctx, desired.GetName(), metav1.GetOptions{})
	if apierrors.IsNotFound(err) {
		_, err = cl.Resource(gvr).Create(ctx, desired, metav1.CreateOptions{})
		return err
	}
	if err != nil {
		return err
	}
	desired.SetResourceVersion(existing.GetResourceVersion())
	_, err = cl.Resource(gvr).Update(ctx, desired, metav1.UpdateOptions{})
	return err
}

// mergeAPIExportResources upserts the owned entries (keyed by group+name) into
// existing. Owned entries win and come first for deterministic output.
//
// Within the API groups init owns (the groups its schema files declare), the
// owned set is authoritative: a pre-existing entry in an owned group whose
// name is no longer owned is a leftover from a renamed/removed resource
// (e.g. agentruns → runs) and is pruned. Entries in foreign groups are
// preserved — those belong to runtime writers (e.g. the infrastructure
// templates controller minting per-template entries in per-template groups).
func mergeAPIExportResources(existing, owned []any) []any {
	parse := func(r any) (group, name string, ok bool) {
		m, ok := r.(map[string]any)
		if !ok {
			return "", "", false
		}
		group, _ = m["group"].(string)
		name, _ = m["name"].(string)
		return group, name, true
	}
	ownedKeys := make(map[string]struct{}, len(owned))
	ownedGroups := make(map[string]struct{}, len(owned))
	for _, r := range owned {
		if group, name, ok := parse(r); ok {
			ownedKeys[group+"/"+name] = struct{}{}
			ownedGroups[group] = struct{}{}
		}
	}
	out := make([]any, 0, len(owned)+len(existing))
	out = append(out, owned...)
	for _, r := range existing {
		group, name, ok := parse(r)
		if !ok {
			out = append(out, r)
			continue
		}
		if _, isOwned := ownedKeys[group+"/"+name]; isOwned {
			continue
		}
		if _, groupOwned := ownedGroups[group]; groupOwned {
			// Stale entry in an init-owned group — prune.
			continue
		}
		out = append(out, r)
	}
	return out
}

// toUnstructured is retained for callers that build typed objects elsewhere.
func toUnstructured(v any) (*unstructured.Unstructured, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	out := &unstructured.Unstructured{}
	if err := json.Unmarshal(data, &out.Object); err != nil {
		return nil, err
	}
	return out, nil
}

var _ = toUnstructured
