import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const app = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

test('defaults and persists the Projects layout through the shared browser preference contract', () => {
  assert.match(app, /import LayoutSelector from '\.\/portalkit\/LayoutSelector\.vue'/)
  assert.match(app, /import \{ readLayoutPreference, writeLayoutPreference, type LayoutMode \} from '\.\/portalkit\/layoutPreference'/)
  assert.match(app, /const PROJECTS_LAYOUT_PREFERENCE_KEY = 'railgrid:portal:app-studio:projects-layout'/)
  assert.match(app, /const projectLayout = ref<LayoutMode>\(readLayoutPreference\(PROJECTS_LAYOUT_PREFERENCE_KEY\)\)/)
  assert.match(app, /watch\(projectLayout, mode => writeLayoutPreference\(PROJECTS_LAYOUT_PREFERENCE_KEY, mode\)\)/)
  assert.match(app, /<LayoutSelector v-model="projectLayout"[^>]*aria-label="Project layout"/)
})

test('shares first-run guidance before the grid/list branches and keeps the gallery in grid mode', () => {
  const guideStart = app.indexOf('<FirstRunGuide')
  const branchStart = app.indexOf('<template v-else-if="projectLayout === \'grid\'">')
  const listStart = app.indexOf('<ResourceTable', branchStart)
  assert.ok(guideStart >= 0 && branchStart > guideStart && listStart > branchStart)

  const guide = app.slice(guideStart, branchStart)
  assert.match(guide, /<FirstRunGuide[\s\S]*v-if="projectsLoaded && !loading && !error && projects\.length === 0"/)
  assert.match(guide, /title="No projects yet\."/)
  assert.match(guide, /description="Start with a project description and review the plan before anything is created\."/)
  assert.match(guide, /primary-label="New project"[\s\S]*@primary="openNewProjectComposer"/)

  const grid = app.slice(branchStart, listStart)
  assert.match(grid, /grid-cols-\[repeat\(auto-fill,minmax\(min\(100%,280px\),360px\)\)\] justify-start/)
  assert.doesNotMatch(grid, /projectInitialPending|showProjectInitialLoading|shimmer/)
  assert.match(grid, /v-for="project in filteredProjects"/)
  assert.match(grid, /v-if="projectThumbnailURLs\[project\.name\]"/)
  assert.match(grid, /@click="enterProject\(project\)"/)
  assert.match(grid, /@click\.stop="requestDeleteProject\(project\)"/)
  assert.match(grid, /<StatusBadge :status="isProjectDeleting\(project\) \? 'Deleting…' : project\.phase \|\| 'Pending'/)
  assert.doesNotMatch(grid, /No projects yet\.|Start with a project description and review the plan before anything is created\./)
  assert.match(grid, /No projects match this search\./)

  const list = app.slice(listStart, app.indexOf('</ResourceTable>', listStart))
  assert.match(list, /:loaded="projectsLoaded"/)
  assert.match(list, /:loading="loading"/)
  assert.doesNotMatch(list, /shimmer/)
})

test('adapts filtered projects into an interactive canonical list with isolated delete actions', () => {
  assert.match(app, /import ResourceTable from '\.\/portalkit\/ResourceTable\.vue'/)
  assert.match(app, /import ResourceTableDeleteButton from '\.\/portalkit\/ResourceTableDeleteButton\.vue'/)
  assert.match(app, /const projectTableRows = computed<Array<Record<string, unknown>>>\(\(\) => filteredProjects\.value\.map/)
  assert.match(app, /name: project\.name,[\s\S]*uid: project\.uid \?\? '',[\s\S]*rowKey: `\$\{project\.name\}:\$\{project\.uid \?\? ''\}`,[\s\S]*description: project\.description \|\| project\.name,[\s\S]*phase: isProjectDeleting\(project\) \? 'Deleting…' : project\.phase \|\| 'Pending',[\s\S]*updated: projectTimestamp\(project\),[\s\S]*deleting: isProjectDeleting\(project\),[\s\S]*_project: project/)
  assert.match(app, /function projectFromTableRow\(row: Record<string, unknown>\): Project \| null/)

  const listStart = app.indexOf('<ResourceTable', app.indexOf('<template v-else-if="projectLayout === \'grid\'">'))
  const list = app.slice(listStart, app.indexOf('</ResourceTable>', listStart))
  assert.match(list, /:columns="projectTableColumns"/)
  assert.match(list, /:rows="projectTableRows"/)
  assert.match(list, /row-key="rowKey"/)
  assert.match(list, /:row-aria-label="\(row\) => row\.deleting[\s\S]*\? `Deleting project[\s\S]*: `Open project/)
  assert.match(list, /@row-click="enterProjectTableRow"/)
  assert.match(list, /<StatusBadge :status="String\(value\)"/)
  assert.match(list, /<ResourceTableDeleteButton[\s\S]*:busy-label="`Deleting project[\s\S]*:busy="deletingProjectName === String\(row\.name\) && deletingProjectUID === String\(row\.uid \|\| ''\)"[\s\S]*:disabled="busy \|\| Boolean\(row\.deleting\)"[\s\S]*@click="requestDeleteProjectTableRow\(row\)"/)
  assert.match(app, /const deletingProjectName = ref\(''\)/)
  assert.match(app, /deletingProjectName\.value = name/)
  assert.match(app, /deletingProjectName\.value = ''/)
  assert.doesNotMatch(list, /:busy="deletingProject"/)
})

test('locks the deleted project and reconciles the accepted request locally', () => {
  assert.match(app, /import \{ toast \} from '\.\/portalkit\/toast'/)
  assert.match(app, /import InlineNotification from '\.\/portalkit\/InlineNotification\.vue'/)
  assert.match(app, /import \{[\s\S]*createProjectDeletionController,[\s\S]*sameProjectIdentity,[\s\S]*\} from '\.\/projectDeletion'/)
  assert.match(app, /function isProjectDeleting\(project: Project \| string\): boolean/)
  assert.match(app, /phase: isProjectDeleting\(project\) \? 'Deleting…' : project\.phase \|\| 'Pending'/)
  assert.match(app, /:disabled="isProjectDeleting\(project\)"[\s\S]*@click="enterProject\(project\)"/)
  assert.match(app, /v-if="isProjectDeleting\(project\)"[\s\S]*role="status"[\s\S]*Deleting…[\s\S]*Cleanup continues in the background\./)
  assert.doesNotMatch(app, /:interactive="true"/)
  assert.match(app, /:interactive="!projectTableRows\.some\(\(row\) => row\.deleting\)"/)
  assert.match(app, /:row-aria-label="\(row\) => row\.deleting[\s\S]*\? `Deleting project[\s\S]*: `Open project/)
  assert.match(app, /:disabled="Boolean\(row\.deleting\)"/)
  assert.match(app, /let projectDeletionPollTimer: number \| undefined/)
  assert.match(app, /function applyProjectList\(projectList: Project\[\]\): Project\[\][\s\S]*projectDeletion\.reconcile/)
  assert.match(app, /function scheduleProjectDeletionPoll\(\)[\s\S]*projectDeletion\.hasPending/)
  assert.match(app, /visible\?\.deleting/)
  assert.match(app, /projectDeletionError[\s\S]*Retry deletion/)

  const deleteStart = app.indexOf('async function requestDeleteProject(project: Project)')
  assert.ok(deleteStart >= 0)
  const deleteFlow = app.slice(deleteStart, app.indexOf('\n\nasync function sendMessage', deleteStart))
  assert.match(deleteFlow, /const target = projectIdentity\(project\)/)
  assert.match(deleteFlow, /const operation = projectDeletion\.begin\(target, projectDeletionContext\(\)\)/)
  assert.match(deleteFlow, /projectDeletion\.matchesCurrent\(operation, projectDeletionContext\(\), visibleProjectNamed\(name\)\)/)
  assert.match(deleteFlow, /invalidateProjectListRequests\(\)/)
  assert.doesNotMatch(deleteFlow, /projects\.value = await api\.listProjects\(props\.ctx\)/)
  assert.match(deleteFlow, /projectDeletion\.acknowledge\(operation\)/)
  assert.match(deleteFlow, /removeProjectFromLocalList\(target\)/)
  assert.doesNotMatch(deleteFlow, /item\.name !== name/)
  const deleteRequestIndex = deleteFlow.indexOf("await api.deleteProject(props.ctx, name, target.uid ?? '')")
  assert.ok(deleteRequestIndex >= 0 && deleteRequestIndex < deleteFlow.indexOf('removeProjectFromLocalList(target)'))
  assert.match(deleteFlow, /toast\('info', `Deletion accepted for \$\{projectLabel\}\. Cleanup continues in the background\.`\)/)
  assert.doesNotMatch(deleteFlow, /toast\('error', failureMessage/)
  assert.match(deleteFlow, /projectDeletionError\.value = failureMessage/)
  assert.match(deleteFlow, /const retryContextFingerprint = operation\.context\.fingerprint/)
  assert.match(deleteFlow, /const retryRoutePath = operation\.context\.routePath/)
  assert.match(deleteFlow, /appContextFingerprint\(props\.ctx\) !== retryContextFingerprint \|\| routePath\.value !== retryRoutePath/)
  assert.match(deleteFlow, /sameProjectIdentity\(target, current\)/)
  assert.match(deleteFlow, /deletingProjectUID\.value = target\.uid \?\? ''/)
  assert.match(deleteFlow, /props\.navigate\(hasRemainingProjects \? '' : CREATE_PROJECT_ROUTE\)/)
  assert.match(deleteFlow, /if \(!hasRemainingProjects && !selectedProjectWasDeleted\) props\.navigate\(CREATE_PROJECT_ROUTE\)/)
})
