import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const app = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
const workbenchTab = await readFile(new URL('./agentkit/AIWorkbenchTab.vue', import.meta.url), 'utf8')
const railgridUI = await readFile(new URL('./agentkit/agent-ui.css', import.meta.url), 'utf8')
const dialog = await readFile(new URL('./ProjectShareDialog.vue', import.meta.url), 'utf8')
const releasePipeline = await readFile(new URL('./ReleasePipeline.vue', import.meta.url), 'utf8')
const promotionState = await readFile(new URL('./promotionState.ts', import.meta.url), 'utf8')
const productionSettings = await readFile(new URL('./useProductionSettings.ts', import.meta.url), 'utf8')

function functionSource(start, end) {
  const startIndex = app.indexOf(start)
  const endIndex = app.indexOf(end, startIndex)
  assert.ok(startIndex >= 0 && endIndex > startIndex)
  return app.slice(startIndex, endIndex)
}

test('emits truthful publishing and access toasts only after current responses', () => {
  const publish = functionSource('async function publishCurrentProject', '\n\n// savePreviewAccess')
  assert.match(publish, /if \(selected\.value\?\.name !== name\) return[\s\S]*productionAccessUpdateToast\(\)[\s\S]*toast\(notice\.kind, notice\.message\)/)

  const preview = functionSource('async function savePreviewAccess', '\n\n// Preview grants')
  assert.match(preview, /if \(selected\.value\?\.name !== name\) return[\s\S]*previewAccessUpdateToast\(state\.converged\)[\s\S]*toast\(notice\.kind, notice\.message\)/)

  const previewGrantCalls = functionSource('async function grantCurrentProjectPreviewAccess', '\n\ninterface PreviewGrantMutation')
  assert.match(previewGrantCalls, /mutation: 'grant'[\s\S]*mutation: 'invite'[\s\S]*mutation: 'revoke'/)
  const previewGrants = functionSource('interface PreviewGrantMutation', '\n\nasync function unpublishCurrentProject')
  assert.match(previewGrants, /if \(selected\.value\?\.name !== name\) return[\s\S]*accessMutationToast\('preview', operation\.mutation, operation\.subject\)[\s\S]*toast\(notice\.kind, notice\.message\)/)

  const unpublish = functionSource('async function unpublishCurrentProject', '\n\nasync function grantCurrentProjectAccess')
  assert.match(unpublish, /if \(selected\.value\?\.name !== name\) return[\s\S]*toast\('ok', 'Production access disabled\.'\)/)

  const productionGrants = functionSource('async function grantCurrentProjectAccess', '\n\nasync function promoteToProd')
  assert.equal((productionGrants.match(/accessMutationToast\('production'/g) ?? []).length, 2)
  assert.equal((productionGrants.match(/toast\(notice\.kind, notice\.message\)/g) ?? []).length, 2)
  assert.equal((productionGrants.match(/if \(selected\.value\?\.name !== name\) return/g) ?? []).length, 2)
  assert.doesNotMatch([publish, preview, previewGrants, unpublish, productionGrants].join('\n'), /toast\('error'/)
})

test('exposes Publishing separately and keeps workspace model config out of Project Settings', () => {
  assert.doesNotMatch(app, /type ProjectSettingsPane/)
  assert.doesNotMatch(app, /projectSettingsPanes/)
  assert.doesNotMatch(app, /aria-label="Project Settings sections"/)
  assert.doesNotMatch(app, /project-settings-tab-model/)
  assert.match(app, /v-if="settingsProject && !publishingInWorkbench && !historyInWorkbench"/)
  assert.match(app, /v-if="!publishingInWorkbench && !historyInWorkbench && !settingsProject"/)
  assert.doesNotMatch(app, /projectSettingsPane === 'production'/)
  assert.doesNotMatch(app, /project-settings-tab-production/)
  assert.doesNotMatch(app, /id: 'builtin:production'/)
  assert.doesNotMatch(app, /builtInTab: 'production'/)
  assert.doesNotMatch(app, /activeWorkbenchTab\?\.kind === 'production'/)
  assert.doesNotMatch(app, /kind: 'production'/)
  assert.match(app, /id: 'builtin:publishing'/)
  assert.match(app, /title: 'Publishing'/)
  assert.match(app, /builtInTab: 'publishing'/)
  assert.match(app, /activeWorkbenchTab\?\.kind === 'publishing'/)
  assert.match(app, /id: 'builtin:history'/)
  assert.match(app, /title: 'History'/)
  assert.match(app, /builtInTab: 'history'/)
  assert.match(app, /activeWorkbenchTab\?\.kind === 'history'/)
})

test('closes project settings before the landing route can render them as an LLM modal', () => {
  const watcherStart = app.indexOf('watch(settingsProject, (project, previousProject) =>')
  const watcherEnd = app.indexOf('\n\nuseEscapeKey', watcherStart)
  assert.ok(watcherStart >= 0 && watcherEnd > watcherStart)
  const watcher = app.slice(watcherStart, watcherEnd)

  assert.match(watcher, /if \(!project && previousProject\)/)
  assert.match(watcher, /showSettings\.value = false/)

  const openStart = app.indexOf('async function openSettings()')
  const openEnd = app.indexOf('function closeSettings()', openStart)
  assert.ok(openStart >= 0 && openEnd > openStart)
  assert.match(app.slice(openStart, openEnd), /showSettings\.value = true/)
})

test('defers project controls until the restored Settings, Publishing, or History host exists', () => {
  assert.match(app, /<Teleport defer :to="projectControlSurfaceTarget">/)
  assert.match(app, /if \(publishingInWorkbench\.value\) return '#app-studio-publishing-host'/)
  assert.match(app, /if \(historyInWorkbench\.value\) return '#app-studio-history-host'/)
  assert.match(app, /if \(settingsInWorkbench\.value\) return '#app-studio-project-settings-host'/)
  const hostStart = app.indexOf('v-show="!projectRouteLoading && !projectRouteFailure && activeWorkbenchTab?.kind === \'settings\'"')
  const loadingPanelStart = app.indexOf('<template v-if="projectRouteLoading">', hostStart)
  assert.ok(hostStart >= 0 && loadingPanelStart > hostStart)
  assert.match(app.slice(hostStart, loadingPanelStart), /id="app-studio-project-settings-host"/)
  assert.match(app.slice(hostStart, loadingPanelStart), /id="app-studio-publishing-host"/)
  assert.match(app.slice(hostStart, loadingPanelStart), /id="app-studio-history-host"/)
  assert.doesNotMatch(app, /v-else-if="activeWorkbenchTab\?\.kind === 'settings'"/)
})

test('keeps New tab in the horizontal tab flow while preserving tablist semantics', () => {
  const headerStart = app.indexOf('<header class="flex h-14')
  const panelStart = app.indexOf('<div\n        v-if="activeWorkbenchTab?.kind === \'launcher\'"', headerStart)
  assert.ok(headerStart >= 0 && panelStart > headerStart)
  const header = app.slice(headerStart, panelStart)
  const groupStart = header.indexOf('<div class="flex min-w-0 flex-1 items-center gap-1">')
  const tabsStart = header.indexOf('<AIWorkbenchTabs', groupStart)
  const tabsEnd = header.indexOf('</AIWorkbenchTabs>', tabsStart)
  const providerStart = header.indexOf('title="Open full provider"', tabsStart)
  assert.ok(groupStart >= 0 && tabsStart > groupStart && tabsEnd > tabsStart && providerStart > tabsEnd)
  assert.match(header.slice(groupStart, providerStart), /flex min-w-0 flex-1 items-center gap-1/)
  const tabstrip = header.slice(tabsStart, tabsEnd)
  assert.match(tabstrip, /:tabs="workbenchTabItems"/)
  assert.match(tabstrip, /aria-label="Workbench tabs"/)
  assert.match(tabstrip, /\slauncher\s/)
  assert.doesNotMatch(tabstrip, /role="tablist"/)
  assert.match(tabstrip, /@dragstart="startWorkbenchTabDragByID"/)
  assert.match(tabstrip, /@dragover="dragOverWorkbenchTabByID"/)
  assert.match(tabstrip, /@drop="dropWorkbenchTabByID"/)
  assert.match(tabstrip, /@dragend="clearWorkbenchTabDragState"/)
  assert.match(tabstrip, /@select="activateWorkbenchTabByID"/)
  assert.match(tabstrip, /@keydown="onWorkbenchTabKeydownByID"/)
  assert.match(tabstrip, /@close="closeWorkbenchTabByID"/)
  assert.match(tabstrip, /@launch="openWorkbenchLauncher"/)
  assert.match(tabstrip, /<template #leading>[\s\S]*<GripVertical[\s\S]*<\/template>/)
  assert.match(tabstrip, /<template #icon="\{ tab \}">[\s\S]*<\/template>/)
  assert.match(tabstrip, /<template #after-label="\{ tab \}">[\s\S]*hasPendingReview[\s\S]*<\/template>/)
  assert.match(tabstrip, /<template #launcher-indicator>[\s\S]*hasPendingReview[\s\S]*<\/template>/)
  assert.doesNotMatch(header, /sticky right-0|role="presentation"/)
  assert.match(workbenchTab, /class="k-workbench-tab"/)
  assert.match(workbenchTab, /class="k-workbench-tab__button"[\s\S]*role="tab"[\s\S]*:aria-selected="selected"[\s\S]*:aria-controls="controls"[\s\S]*:tabindex="tabindex"[\s\S]*:title="title"/)
  assert.match(workbenchTab, /<slot name="leading" \/>[\s\S]*<span class="k-workbench-tab__label"><slot \/><\/span>[\s\S]*<slot name="after-label" \/>[\s\S]*<slot name="trailing" \/>/)
  const tabRecipeStart = railgridUI.indexOf('.k-workbench-tab {')
  const tabRecipeEnd = railgridUI.indexOf('button.k-workbench-tab {', tabRecipeStart)
  assert.ok(tabRecipeStart >= 0 && tabRecipeEnd > tabRecipeStart)
  assert.match(railgridUI.slice(tabRecipeStart, tabRecipeEnd), /max-width: 240px/)
  assert.match(header, /title="Open full provider"[\s\S]*@click="openToolFull"/)
})

test('anchors Share beside the Workbench toggle and preserves its dialog focus contract', () => {
  const titlebarStart = app.indexOf('<header data-app-studio-titlebar')
  const titlebarEnd = app.indexOf('</header>', titlebarStart)
  assert.ok(titlebarStart >= 0 && titlebarEnd > titlebarStart)
  const titlebar = app.slice(titlebarStart, titlebarEnd)
  const toggleStart = titlebar.indexOf('data-app-studio-workbench-toggle')
  const toggleButtonStart = titlebar.lastIndexOf('<button', toggleStart)
  const shareStart = titlebar.indexOf('ref="shareButtonRef"')
  const shareButtonStart = titlebar.lastIndexOf('<button', shareStart)
  assert.ok(toggleButtonStart >= 0 && shareStart > toggleButtonStart)
  assert.match(titlebar.slice(toggleButtonStart, shareStart), /aria-expanded="workbenchVisible"/)
  assert.match(titlebar.slice(toggleButtonStart, shareStart), /aria-controls="app-studio-workbench-pane"/)
  assert.ok(shareButtonStart >= 0 && shareButtonStart < shareStart)
  assert.match(titlebar.slice(shareButtonStart), /title="Share project"/)
  assert.match(titlebar.slice(shareButtonStart), /aria-label="Share project"/)
  assert.match(titlebar.slice(shareButtonStart), /:disabled="!selected"/)
  assert.match(titlebar.slice(shareButtonStart), /@click="openShareDialog"/)
  assert.match(titlebar.slice(shareButtonStart), /border-accent bg-accent/)
  assert.match(titlebar.slice(shareButtonStart), />\s*<span>Share<\/span>/)

  const workbenchHeaderStart = app.indexOf('<header class="flex h-14')
  const workbenchHeaderEnd = app.indexOf('</header>', workbenchHeaderStart)
  assert.ok(workbenchHeaderStart >= 0 && workbenchHeaderEnd > workbenchHeaderStart)
  assert.doesNotMatch(app.slice(workbenchHeaderStart, workbenchHeaderEnd), /aria-label="Share project"/)
  assert.equal((app.match(/ref="shareButtonRef"/g) ?? []).length, 1)
  const closeStart = app.indexOf('function closeShareDialog()')
  const closeEnd = app.indexOf('function openPublishingFromShare()', closeStart)
  assert.ok(closeStart >= 0 && closeEnd > closeStart)
  assert.match(app, /function openShareDialog\(event\?: Event\)[\s\S]*event\?\.currentTarget instanceof HTMLElement/)
  assert.match(app.slice(closeStart, closeEnd), /restoreShareDialogFocus\(\)/)
  assert.match(app, /function restoreShareDialogFocus\(\)[\s\S]*target\?\.isConnected[\s\S]*else shareButtonRef\.value\?\.focus\(\)/)
})

test('presents Publishing as a release review with separate configuration and access ownership', () => {
  const productionStart = app.indexOf('ref="publishingPaneRef"')
  const historyStart = app.indexOf('v-else-if="historyInWorkbench"', productionStart)
  const productionEnd = historyStart
  assert.ok(productionStart >= 0 && historyStart > productionStart && productionEnd > productionStart)
  const pane = app.slice(productionStart, productionEnd)
  assert.match(pane, /aria-label="Production overview"/)
  assert.match(pane, /aria-label="Release ready for production"/)
  assert.match(pane, /Verified release/)
  assert.match(pane, /Image verified/)
  assert.doesNotMatch(pane, /Latest build commit|Built images/)
  assert.match(pane, /Open app/)
  assert.match(pane, /aria-label="Technical details"/)
  assert.match(pane, /<ReleasePipeline[\s\S]*:pipeline="releasePipeline"[\s\S]*@refresh="refreshProduction"/)
  assert.match(pane, /Production is running/)
  assert.match(pane, /bg-success-subtle[^\n]*text-success/)
  assert.match(pane, /publishing\?\.publication\?\.error && !publishing\?\.publication\?\.ready/)
  assert.match(pane, /publishingActionError[^\n]*text-danger/)
  // Share is the single user-facing owner for visibility and grants. The
  // generic schema form must not duplicate template-native access controls.
  assert.match(pane, /Manage access/)
  assert.match(pane, /@click="openShareDialog"/)
  assert.doesNotMatch(pane, /aria-label="Production visibility"|@change="onProductionVisibilityChange"/)
  assert.doesNotMatch(pane, /Disable access/)
  assert.doesNotMatch(pane, /role="radiogroup"/)
  assert.doesNotMatch(pane, /@click="publishCurrentProject"/)
  assert.match(pane, /<ProductionForm[\s\S]*:schema="promotion\?\.productionSchema \?\? null"/)
  assert.match(pane, /Template-owned runtime settings only\./)
  assert.match(pane, /Deployment configuration/)
  assert.match(pane, /Save configuration and redeploy/)
  assert.match(pane, /These values will be reviewed and applied with the first deployment\./)
  assert.match(pane, /aria-label="Current production release"/)
  assert.match(pane, /@click="redeployCurrentProduction"/)
  assert.match(pane, /@click="openProductionDeployReview\(latestDeployableRelease\)"/)
  assert.match(pane, /@click="confirmProductionDeploy"/)
  assert.match(pane, /Deploy this release to production\?/)
  assert.match(pane, /First production deployment/)
  assert.match(pane, /Current production stays online until this exact release is observed/)
  assert.match(pane, /Starts invite-only/)
  assert.match(pane, /:disabled="promotionBusy \|\| !promotionValuesDirty \|\| !canRedeployCurrentProduction"/)
  assert.doesNotMatch(pane, /<ReleasePicker/)
  assert.doesNotMatch(pane, /<textarea[^>]*promotionValuesText/)
})

test('refreshes release evidence in every scheduled promotion poll', () => {
  const pollStart = app.indexOf('async function pollPromotionAndReleases()')
  const scheduleStart = app.indexOf('function schedulePromotionPoll()', pollStart)
  const scheduleEnd = app.indexOf('\n\nfunction clearPublishingPoll()', scheduleStart)
  assert.ok(pollStart >= 0 && scheduleStart > pollStart && scheduleEnd > scheduleStart)

  const poll = app.slice(pollStart, scheduleStart)
  const schedule = app.slice(scheduleStart, scheduleEnd)
  assert.match(poll, /Promise\.allSettled\(\[loadPromotionStatus\(false\), loadReleases\(\)\]\)/)
  assert.match(poll, /selected\.value\?\.name === projectName\) schedulePromotionPoll\(\)/)
  assert.equal((schedule.match(/pollPromotionAndReleases/g) ?? []).length, 4)
  assert.doesNotMatch(schedule, /setTimeout\([^\n]*loadPromotion/)
  assert.match(app, /async function loadPromotionStatus\(scheduleNext: boolean\)/)
  assert.match(app, /if \(scheduleNext\) schedulePromotionPoll\(\)/)
  assert.match(app, /async function loadPromotion\(\) \{[\s\S]*await loadPromotionStatus\(true\)[\s\S]*\}/)
})

test('keeps Git filesystem restoration in History and out of production promotion', () => {
  const historyStart = app.indexOf('v-else-if="historyInWorkbench"')
  const historyEnd = app.indexOf('v-if="!publishingInWorkbench && !historyInWorkbench', historyStart)
  assert.ok(historyStart >= 0 && historyEnd > historyStart)
  const pane = app.slice(historyStart, historyEnd)
  assert.match(pane, /aria-label="History"/)
  assert.match(pane, />History<\/h2>/)
  assert.match(pane, /<ProjectHistory[\s\S]*:commits="historyCommits"[\s\S]*@restore="restoreProjectHistory"/)
  assert.match(pane, /Return the current project filesystem to an earlier Git commit/)
  assert.doesNotMatch(pane, /load-from-git|hydrateDevelopmentWorkspace|Load from Git/i)
  assert.doesNotMatch(pane, /ReleasePicker|promoteToProd|production images|releaseID/)
  assert.match(app, /const expectedSourceRevision = selected\.value\?\.sourceRevision \?\? 0/)
  assert.match(app, /api\.restoreWorkspace\(props\.ctx, projectName, commitSHA, expectedSourceRevision\)/)
  assert.match(app, /if \(selected\.value && result\.sourceRevision\) selected\.value\.sourceRevision = result\.sourceRevision/)
})

test('redeploying settings is bound to the current production release', () => {
  assert.match(app, /const currentProductionRelease = computed\(\(\) => releases\.value\.find\(\(release\) => release\.live && releaseHasPromotionEvidence\(release\)\) \?\? null\)/)
  assert.match(app, /void promoteToProd\(true, currentProductionRelease\.value\)/)
  assert.match(app, /const canRedeployCurrentProduction = computed\(\(\) => Boolean\([\s\S]*currentProductionRelease\.value[\s\S]*productionBinding\.value/)
  assert.match(app, /The current production release is unavailable\. Refresh Publishing to retry\./)
  const promoteStart = app.indexOf('async function promoteToProd(')
  const promoteEnd = app.indexOf('\n\nfunction redeployCurrentProduction', promoteStart)
  assert.ok(promoteStart >= 0 && promoteEnd > promoteStart)
  const promote = app.slice(promoteStart, promoteEnd)
  assert.match(promote, /const release = requestedRelease \?\? latestDeployableRelease\.value/)
  assert.match(promote, /if \(!name \|\| !releaseHasPromotionEvidence\(release\) \|\| !canPromoteRelease\(release\)\) return/)
  assert.doesNotMatch(promote, /selectedHistory|canPromoteSelectedRelease\.value/)
})

test('renders release progress as an announced five-stage pipeline without image evidence details', () => {
  for (const label of ['Commit', 'Build', 'Verify images', 'Deploy', 'Access policy']) {
    assert.match(promotionState, new RegExp(`label: '${label}'`))
  }
  assert.match(releasePipeline, /aria-label="Release pipeline"/)
  assert.doesNotMatch(releasePipeline, /aria-label="Release image evidence"/)
  assert.match(releasePipeline, /aria-live=/)
  assert.match(releasePipeline, /pipeline\.state === 'failed' \? 'alert' : 'status'/)
  assert.match(releasePipeline, />View build<\/a>/)
  assert.match(releasePipeline, /Check again/)
  assert.match(releasePipeline, /Taking longer than usual/)
  assert.doesNotMatch(releasePipeline, /Expected package and tag/)
  assert.doesNotMatch(releasePipeline, /Re-run build|Reconnect GitHub/)
})

test('keeps publication success deployment-scoped while Live remains URL-dependent', () => {
  assert.match(app, /useProductionSettings\(\{/)
  assert.match(productionSettings, /const productionPublicationReady = computed\(\(\) => Boolean\([\s\S]*productionBinding\.value[\s\S]*productionDeployment\.value\.ready[\s\S]*input\.publishing\.value\?\.published[\s\S]*input\.publishing\.value\.publication\?\.ready[\s\S]*\)\)/)
  assert.match(productionSettings, /return \{ label: productionURL\.value \? 'Live' : 'Ready', tone: 'success' \}/)
  assert.match(productionSettings, /productionPublicationReady\.value && !productionURL\.value/)
  assert.match(productionSettings, /const productionPublicationStatus = computed<ProductionStatusPresentation>\(\(\) => \{[\s\S]*if \(productionPublicationReady\.value\)[\s\S]*tone: 'success'/)
  assert.match(productionSettings, /if \(input\.publishing\.value\?\.publication\?\.error\) return \{ label: 'Error', tone: 'danger' \}/)
  const overviewStart = productionSettings.indexOf('const productionOverview = computed')
  const overviewEnd = productionSettings.indexOf('const productionOverviewDescription = computed', overviewStart)
  assert.ok(overviewStart >= 0 && overviewEnd > overviewStart)
  assert.match(productionSettings.slice(overviewStart, overviewEnd), /productionPublicationReady\.value[\s\S]*input\.publishing\.value\.publication\?\.error/)
  assert.match(productionSettings, /The publication is ready; the production link is still being resolved\./)
  // A stale publication object must not make the not-yet-deployed panel claim
  // that the app is ready. The binding/readiness guard above is the boundary.
  assert.match(productionSettings, /if \(!productionBinding\.value\) return \{ label: 'Not deployed'/)
})

test('routes sharing through the modular dialog and current access contracts only', () => {
  assert.match(app, /import ProjectShareDialog from '\.\/ProjectShareDialog\.vue'/)
  assert.match(app, /<ProjectShareDialog[\s\S]*v-model:mode="shareMode"[\s\S]*@save="publishCurrentProject"[\s\S]*@grant="grantCurrentProjectAccess"[\s\S]*@invite="inviteCurrentProjectAccess"[\s\S]*@revoke="revokeCurrentProjectAccess"[\s\S]*@disable="unpublishCurrentProject"/)
  assert.match(app, /@open-publishing="openPublishingFromShare"/)
  assert.match(app, /const mode = shareMode\.value[\s\S]*api\.publishProject\(props\.ctx, name, mode\)/)
  assert.match(dialog, /Production app/)
  assert.match(dialog, /Development preview/)
  assert.match(dialog, /value: 'restricted'/)
  assert.match(dialog, /value: 'public'/)
  assert.match(dialog, /Invited people/)
  assert.match(dialog, /availableMembers/)
  assert.match(dialog, /activeGrants/)
  assert.match(dialog, /savedRestricted/)
  assert.match(dialog, /canAddMember/)
  assert.match(dialog, /Save Production access before managing people\./)
  assert.match(dialog, /const canSaveProduction = computed\(\(\) => \(/)
  assert.match(dialog, /const canSavePreview = computed\(\(\) => \(/)
  assert.match(dialog, /Production link/)
  assert.match(dialog, /Preview link/)
  assert.match(dialog, /open-publishing/)
  assert.match(dialog, /Set up production/)
  assert.match(dialog, /Done/)
  assert.match(dialog, /Save production access/)
  assert.match(dialog, /Save preview access/)
  assert.match(dialog, /Enable production access/)
  assert.match(dialog, /Revoke/)
  assert.match(dialog, /Disable access/)
  assert.match(dialog, /dialogCloseButton/)
  assert.match(dialog, /focusDialog/)
  for (const inventedCapability of ['owner', 'group']) {
    assert.doesNotMatch(dialog, new RegExp(`\\b${inventedCapability}\\b`, 'i'))
  }
  // Email appears ONLY as the explicit invite affordance (pre-provisioned
  // pending user, adopted at first sign-in) — grants themselves are still
  // written against stable User names, never email identities.
  assert.match(dialog, /canInvite/)
  assert.match(dialog, /emit\('invite', email\)/)
  assert.match(dialog, /New users join the Workspace at first sign-in\./)
  assert.doesNotMatch(dialog, /member\.role|grant\.role|role\s*:/i)

  const productionSave = dialog.slice(dialog.indexOf('function saveProductionAccess()'), dialog.indexOf('function savePreviewAccess()'))
  const previewSave = dialog.slice(dialog.indexOf('function savePreviewAccess()'), dialog.indexOf('function inviteByEmail()'))
  assert.match(productionSave, /emit\('save'\)/)
  assert.doesNotMatch(productionSave, /save-preview/)
  assert.match(previewSave, /emit\('save-preview'\)/)
  assert.doesNotMatch(previewSave, /emit\('save'\)/)
})

test('suppresses stale publication errors for a ready URL and keeps copy actions destination-scoped', () => {
  assert.match(dialog, /props\.publication\?\.error && !props\.publication\?\.ready/)
  assert.match(dialog, /props\.publication\?\.ready \? 'Ready' : 'Pending'/)
  assert.match(dialog, /v-if="published && publication\?\.error && !publication\?\.ready"[^>]*text-danger[^>]*role="alert"/)
  assert.match(dialog, /v-if="error"[^>]*text-danger/)
  const footerStart = dialog.indexOf('<footer')
  const copyStart = dialog.indexOf("copyChannelLink('production')")
  assert.ok(copyStart >= 0 && footerStart > copyStart)
  assert.match(dialog, /copyTextWithFallback\(value\)/)
  assert.match(dialog, /props\.productionURL\.trim\(\) \|\| props\.publication\?\.url\?\.trim\(\)/)
  assert.match(dialog, /aria-label="Production app link"/)
  assert.match(dialog, /productionLinkInput\.value : previewLinkInput\.value/)
  assert.match(dialog, /productionCopyState === 'copied' \? 'Copied' : 'Copy'/)
  assert.match(dialog, /Select the link and copy it manually\./)
})

test('keeps Share independently useful through partial loads and traps modal keyboard input', () => {
  assert.match(app, /Promise\.allSettled\(\[\s*api\.getPublishing[\s\S]*api\.listPublishingMembers/)
  assert.match(app, /publishingLoadState\.value = stateSucceeded && membersSucceeded[\s\S]*'partial'[\s\S]*'error'/)
  assert.match(app, /:load-state="publishingLoadState"/)
  assert.match(app, /@retry="retryPublishing"/)
  assert.match(dialog, /loadState === 'error'/)
  assert.match(dialog, /loadState === 'partial'/)
  assert.match(dialog, /membersError/)
  assert.match(dialog, /@click="emit\('retry'\)"/)
  assert.match(dialog, /event\.defaultPrevented/)
  assert.match(dialog, /event\.defaultPrevented \|\| confirmState\.open/)
  assert.match(dialog, /querySelectorAll<HTMLElement>/)
  assert.match(dialog, /event\.shiftKey && document\.activeElement === first/)
})

test('keeps members from a state-failed initial load but blocks publication mutations', () => {
  assert.match(app, /const publishingStateAvailable = ref\(false\)/)
  const loadStart = app.indexOf('async function loadPublishing()')
  const loadEnd = app.indexOf('\n\nfunction retryPublishing()', loadStart)
  assert.ok(loadStart >= 0 && loadEnd > loadStart)
  const load = app.slice(loadStart, loadEnd)
  assert.match(load, /const stateSucceeded = stateResult\.status === 'fulfilled'/)
  assert.match(load, /const membersSucceeded = membersResult\.status === 'fulfilled'/)
  assert.match(load, /if \(membersSucceeded\) \{[\s\S]*publishingMembers\.value = membersResult\.value[\s\S]*publishingMembersLoaded\.value = true/)
  assert.match(load, /if \(stateSucceeded\) \{[\s\S]*publishingStateAvailable\.value = true/)
  assert.match(load, /const stateAvailable = publishingStateAvailable\.value/)
  assert.doesNotMatch(load, /if \(!stateSucceeded\) \{[\s\S]*publishingStateAvailable\.value = false/)
  assert.match(load, /publishingLoadState\.value = stateSucceeded && membersSucceeded[\s\S]*'partial'[\s\S]*'error'/)
  assert.match(app, /:publication-state-available="publishingStateAvailable"/)
  for (const action of [
    'publishCurrentProject',
    'unpublishCurrentProject',
    'grantOrInviteProjectAccess',
    'revokeCurrentProjectAccess',
  ]) {
    const actionStart = app.indexOf(`async function ${action}`)
    assert.ok(actionStart >= 0, `${action} exists`)
    const nextAction = app.indexOf('\nasync function ', actionStart + 1)
    const actionSource = app.slice(actionStart, nextAction >= 0 ? nextAction : undefined)
    assert.match(actionSource, /!publishingStateAvailable\.value/, `${action} requires known publication state`)
  }
  assert.match(dialog, /<fieldset class="grid gap-2" :disabled="busy \|\| !publicationStateAvailable">/)
  assert.match(dialog, /props\.publicationStateAvailable &&[\s\S]*\(props\.published \|\| props\.productionReady\)/)
})

test('published apps can change access anytime; only first publish waits for production readiness', () => {
  // An access flip on a promoted app is an intent write — a rolling or
  // briefly-unready deployment must not block it (the publication state
  // machine reports Pending honestly while the gate converges).
  assert.match(dialog, /const canSaveProduction = computed\(\(\) => \(\s*!props\.loading && props\.loadState !== 'error' && !props\.busy &&\s*props\.publicationStateAvailable && \(props\.published \|\| props\.productionReady\)/)
  assert.match(dialog, /const canSavePreview = computed\(\(\) => \(\s*!props\.loading && props\.loadState !== 'error' && !props\.busy && previewDirty\.value/)
  // The deploy-first warning is reserved for never-promoted projects.
  assert.match(dialog, /v-if="!published && !productionReady"/)
  assert.match(dialog, /const modeDirty = computed\(\(\) => props\.published && selectedMode\.value !== initialMode\.value\)/)
  assert.match(dialog, /const canAddMember = computed\(\(\) => \(\s*props\.publicationStateAvailable && savedRestricted\.value && !modeDirty\.value/s)
})

test('restores the Share trigger after confirmed disable and uses one production-surface polling transition', () => {
  const unpublishStart = app.indexOf('async function unpublishCurrentProject')
  const unpublishEnd = app.indexOf('async function grantCurrentProjectAccess', unpublishStart)
  assert.ok(unpublishStart >= 0 && unpublishEnd > unpublishStart)
  const unpublish = app.slice(unpublishStart, unpublishEnd)
  assert.match(unpublish, /let disableSucceeded = false/)
  assert.match(unpublish, /publishingActionBusy\.value = false[\s\S]*if \(disableSucceeded\) closeShareDialog\(\)/)
  assert.doesNotMatch(unpublish, /shareDialogOpen\.value = false/)

  assert.match(app, /const productionSurfaceActive = computed\(\(\) => publishingInWorkbench\.value \|\| shareDialogOpen\.value\)/)
  assert.doesNotMatch(app, /productionSurfaceActive[^\n]*historyInWorkbench/)
  assert.match(app, /if \(releasePipeline\.value\.transitional\)/)
  assert.match(app, /releaseTakingLonger\.value \? PROMOTION_POLL_MAX_DELAY_MS : promotionPollDelay\(0\)/)
  const watcherStart = app.indexOf('watch(\n  () => [productionSurfaceActive.value')
  const watcherEnd = app.indexOf('\n\n onBeforeUnmount', watcherStart)
  assert.ok(watcherStart >= 0)
  const watcher = app.slice(watcherStart, watcherEnd > watcherStart ? watcherEnd : watcherStart + 1800)
  assert.match(watcher, /surfaceOrProjectChanged/)
  assert.match(watcher, /clearPromotionPoll\(\)/)
  assert.match(watcher, /clearPublishingPoll\(\)/)
  assert.match(app, /const publishingInWorkbench = computed\(\(\) => activeWorkbenchTab\.value\?\.kind === 'publishing'\)/)
  const openStart = app.indexOf('function openShareDialog')
  const openEnd = app.indexOf('function closeShareDialog', openStart)
  assert.ok(openStart >= 0 && openEnd > openStart)
  assert.doesNotMatch(app.slice(openStart, openEnd), /loadPromotion|loadPublishing/)

  const settingsStart = app.indexOf('function openPublishingFromShare')
  const settingsEnd = app.indexOf('function workbenchPersistenceContext', settingsStart)
  assert.ok(settingsStart >= 0 && settingsEnd > settingsStart)
  const settingsHandler = app.slice(settingsStart, settingsEnd)
  assert.match(settingsHandler, /shareDialogOpen\.value = false/)
  assert.match(settingsHandler, /openBuiltInWorkbenchTab\('publishing'\)/)
  assert.match(settingsHandler, /publishingPaneRef\.value\?\.focus\(\)/)
  assert.doesNotMatch(settingsHandler, /projectSettingsPane/)
  assert.doesNotMatch(settingsHandler, /shareButtonRef/)

  const closeStart = app.indexOf('function closeShareDialog')
  const closeEnd = app.indexOf('function openPublishingFromShare', closeStart)
  assert.ok(closeStart >= 0 && closeEnd > closeStart)
  const closeHandler = app.slice(closeStart, closeEnd)
  assert.match(closeHandler, /shareDialogOpen\.value = false[\s\S]*if \(!publishingInWorkbench\.value\)/)
  assert.doesNotMatch(closeHandler, /kind !== 'production'/)
})

test('layers the shared confirm dialog at body and restores Disable access focus on cancel', () => {
  const pkDialogStart = app.indexOf('<ConfirmDialog />')
  const shareStart = app.indexOf('<ProjectShareDialog')
  assert.ok(pkDialogStart >= 0 && shareStart > pkDialogStart)
  assert.match(app.slice(Math.max(0, pkDialogStart - 80), pkDialogStart + 40), /<Teleport to="body">[\s\S]*<ConfirmDialog \/>/)

  const unpublishStart = app.indexOf('async function unpublishCurrentProject')
  const unpublishEnd = app.indexOf('async function grantCurrentProjectAccess', unpublishStart)
  assert.ok(unpublishStart >= 0 && unpublishEnd > unpublishStart)
  const unpublish = app.slice(unpublishStart, unpublishEnd)
  assert.match(unpublish, /const disableAccessTrigger = document\.activeElement instanceof HTMLElement \? document\.activeElement : null/)
  assert.match(unpublish, /const confirmed = await confirmDialog\(/)
  assert.match(unpublish, /if \(!confirmed\) \{[\s\S]*await nextTick\(\)[\s\S]*disableAccessTrigger\?\.isConnected[\s\S]*disableAccessTrigger\.focus\(\)[\s\S]*return/)
})

test('closes inline Settings by removing its active tab through the normalized fallback', () => {
  const closeStart = app.indexOf('function closeSettings()')
  const closeEnd = app.indexOf('\n\nfunction syncProjectSettingsForm', closeStart)
  assert.ok(closeStart >= 0 && closeEnd > closeStart)
  const close = app.slice(closeStart, closeEnd)
  assert.ok(close.includes('showSettings.value = false'))
  assert.ok(close.includes("workbench.value.tabs.some((tab) => tab.id === 'settings')"))
  assert.ok(close.includes("closeWorkbenchTabByID('settings')"))
  assert.ok(app.includes('@click.self="!settingsSurfaceInline && closeSettings()"'))
  const escapeStart = app.indexOf('useEscapeKey(() => {')
  const escapeEnd = app.indexOf('\n})', escapeStart)
  assert.ok(escapeStart >= 0 && escapeEnd > escapeStart)
  assert.ok(app.slice(escapeStart, escapeEnd).includes('closeSettings()'))

  const tabCloseStart = app.indexOf('function closeWorkbenchTabByID')
  const tabCloseEnd = app.indexOf('\n\nfunction startWorkbenchTabDrag', tabCloseStart)
  assert.ok(tabCloseStart >= 0 && tabCloseEnd > tabCloseStart)
  assert.ok(app.slice(tabCloseStart, tabCloseEnd).includes("workbench.value = closeWorkbenchTab(workbench.value, tabID)"))
})

test('guards project settings saves by serial, project, and context without stale busy cleanup', () => {
  const saveStart = app.indexOf('async function saveProjectSettings()')
  const saveEnd = app.indexOf('\n\nfunction enterProject', saveStart)
  assert.ok(saveStart >= 0 && saveEnd > saveStart)
  const save = app.slice(saveStart, saveEnd)
  for (const contract of [
    'const saveSerial = ++projectSettingsSaveSerial',
    'const projectName = project.name',
    'const contextFingerprint = projectContextFingerprint(props.ctx)',
    'saveSerial === projectSettingsSaveSerial',
    'contextFingerprint === projectContextFingerprint(props.ctx)',
    'selected.value?.name === projectName',
  ]) assert.ok(save.includes(contract), contract)
  const requestIndex = save.indexOf('await api.updateProjectDetails')
  const responseGuardIndex = save.indexOf('if (!isCurrentSave()) return', requestIndex)
  const catchIndex = save.indexOf('} catch (e) {')
  const catchGuardIndex = save.indexOf('if (!isCurrentSave()) return', catchIndex)
  const finallyIndex = save.indexOf('} finally {')
  assert.ok(requestIndex >= 0 && responseGuardIndex > requestIndex)
  assert.ok(catchIndex > responseGuardIndex && catchGuardIndex > catchIndex)
  assert.ok(finallyIndex > catchGuardIndex)
  assert.ok(save.slice(finallyIndex).includes('if (isCurrentSave()) projectSettingsSaving.value = false'))
})

test('settles terminal project-list failures and keeps a visible Retry action', () => {
  const loadStart = app.indexOf('async function load()')
  const catchStart = app.indexOf('} catch (e) {', loadStart)
  const finallyStart = app.indexOf('} finally {', catchStart)
  assert.ok(loadStart >= 0 && catchStart > loadStart && finallyStart > catchStart)
  const loadCatch = app.slice(catchStart, finallyStart)
  assert.ok(loadCatch.indexOf('clearInitializationRetry()') < loadCatch.indexOf('initializing.value = false'))
  assert.ok(loadCatch.includes("initializingMessage.value = 'App Studio is preparing this workspace...'"))
  assert.ok(loadCatch.includes('projectsLoaded.value = true'))

  const landingStart = app.indexOf('<div v-else-if="!isBuilderVisible"')
  const errorStart = app.indexOf('<div v-if="error && !projectDeletionError"', landingStart)
  const gridStart = app.indexOf('<template v-if="projectLayout === \'grid\'">', errorStart)
  assert.ok(landingStart >= 0 && errorStart > landingStart && gridStart > errorStart)
  const listError = app.slice(errorStart, gridStart)
  assert.ok(listError.includes('@click="load"'))
  assert.match(app, /const projectIndexRoutePending = computed\(\(\) =>[\s\S]*isProjectIndexRoute\.value[\s\S]*projects\.value\.length === 0[\s\S]*emptyProjectRedirectPending\.value/)
})

test('commits a thread selection only after history succeeds and clears the pending state', () => {
  const selectStart = app.indexOf('async function selectAssistantThread')
  const selectEnd = app.indexOf('\n\nasync function createAssistantThread', selectStart)
  assert.ok(selectStart >= 0 && selectEnd > selectStart)
  const select = app.slice(selectStart, selectEnd)
  const requestIndex = select.indexOf('const page = await api.listAssistantThreadItemPage')
  const commitIndex = select.indexOf('activeAssistantThreadID.value = threadID')
  assert.ok(requestIndex >= 0 && commitIndex > requestIndex)
  assert.ok(select.includes('const previousThreadID = activeAssistantThreadID.value'))
  assert.ok(select.includes('const threadHistoryLatchOwner = beginThreadHistoryLatch()'))
  assert.ok(select.includes('releaseThreadHistoryLatch(threadHistoryLatchOwner, threadID)'))
})

test('restores the opening Share mode on every unsaved exit while reflecting successful saves', () => {
  const closeStart = dialog.indexOf('function close()')
  const settingsStart = dialog.indexOf('function openPublishing()', closeStart)
  assert.ok(closeStart >= 0 && settingsStart > closeStart)
  const close = dialog.slice(closeStart, settingsStart)
  assert.ok(close.includes('restoreProductionDraft()'))
  assert.ok(close.includes('restorePreviewDraft()'))

  const settingsEnd = dialog.indexOf('\n\nfunction addMember', settingsStart)
  assert.ok(settingsEnd > settingsStart)
  const settingsExit = dialog.slice(settingsStart, settingsEnd)
  assert.ok(settingsExit.includes('restoreProductionDraft()'))
  assert.ok(settingsExit.includes('restorePreviewDraft()'))
  assert.ok(settingsExit.includes("emit('open-publishing')"))

  assert.match(dialog, /function restorePreviewDraft\(\)[\s\S]*emit\('update:previewMode', props\.previewSavedMode\)/)

  const parentCloseStart = app.indexOf('function closeShareDialog()')
  const parentSettingsStart = app.indexOf('function openPublishingFromShare()', parentCloseStart)
  assert.ok(parentCloseStart >= 0 && parentSettingsStart > parentCloseStart)
  assert.ok(app.slice(parentCloseStart, parentSettingsStart).includes('restoreShareModeFromPublication()'))
  const publishStart = app.indexOf('async function publishCurrentProject()')
  const publishEnd = app.indexOf('\n\nasync function unpublishCurrentProject', publishStart)
  assert.ok(publishEnd > publishStart)
  assert.ok(app.slice(publishStart, publishEnd).includes("shareMode.value = state.publication?.mode === 'public' ? 'public' : mode"))
})

test('keeps Preview edits dirty until the API acknowledges the desired mode', () => {
  assert.match(dialog, /previewSavedMode\?: ProjectPublishingMode/)
  assert.match(dialog, /sharePreviewAccessDraftState\([\s\S]*selectedPreviewMode\.value,[\s\S]*props\.previewSavedMode,[\s\S]*props\.previewSupported,[\s\S]*props\.previewConverged/)
  assert.match(dialog, /const previewDirty = computed\(\(\) => previewDraftState\.value\.dirty\)/)
  assert.match(dialog, /const previewPending = computed\(\(\) => previewDraftState\.value\.pending\)/)
  assert.doesNotMatch(dialog, /watch\(\(\) => props\.previewMode/)
  assert.doesNotMatch(dialog, /initialPreviewMode|previewModeTouched/)
  assert.match(app, /:preview-saved-mode="previewAccess\?\.mode === 'public' \? 'public' : 'restricted'"/)

  const saveStart = app.indexOf('async function savePreviewAccess()')
  const saveEnd = app.indexOf('async function grantCurrentProjectPreviewAccess', saveStart)
  assert.ok(saveStart >= 0 && saveEnd > saveStart)
  const save = app.slice(saveStart, saveEnd)
  assert.match(save, /previewAccess\.value = state/)
  assert.match(save, /previewMode\.value = state\.mode === 'public' \? 'public' : 'restricted'/)
})

test('Publishing explains Git prerequisites and links unconnected projects to settings', () => {
  const start = app.indexOf('aria-label="Production overview"')
  const end = app.indexOf('<ProductionSettingsLoadingShell', start)
  const overview = app.slice(start, end)
  assert.match(overview, /selected\?\.repository\?\.ref \? productionOverviewDescription/)
  assert.match(overview, /Production publishing requires a connected repository, a Git commit, and a successful build/)
  assert.match(overview, /v-if="selected && !selected\.repository\?\.ref"[^>]*@click="openSettings">Connect Git/)
})
