// ApiClient is the agents micro-frontend's single data entry point.
//
// It has two halves. Tenant OBJECTS — Agent, Schedule, Connection, Toolset,
// Trigger, the model-credential Secrets and the workspace's MCPServer — are
// bound APIs in the tenant's own workspace, so they are read and written
// straight against kcp through portalkit's kube client; that half lives in
// resources.ts and is delegated to below. Everything else is a VERB the
// provider backend has to run because it needs the engine, a server-held
// credential, or Postgres-backed state that is not a kcp object at all.
//
// Every one of those verbs is a kcp CUSTOM SUBRESOURCE on the bound kind —
// "{resource}/{verb}" on the agents APIExport — and is addressed like any other
// kube path on the hub's kcp front door, built by portalkit's kubeVerbPath:
//
//	/clusters/{cluster}/apis/agents.railgrid.ai/v1alpha1/{resource}/{name}/{verb}[/{tail}]
//
// kcp authenticates the caller, authorizes the verb with ordinary RBAC and
// forwards the request to the provider. There is no /api/* surface left and no
// hub-proxied spelling of a verb; only /oauth/providers and /mcp still go
// through the hub's service proxy (serviceBase). The cluster is
// railgridContext.tenant — the same kcp logical-cluster ID the kube half
// addresses — so both halves move together on a workspace switch and neither
// can be pointed at a workspace the other is not looking at.
//
// A consequence worth stating: the grammar addresses an OBJECT, so the feeds
// that used to be workspace-wide (activity, inbox, usage, the event stream) are
// per-agent verbs, and this client fans out over the agents the caller can see
// and merges the results. That is the honest shape — a caller sees exactly the
// agents they may see — but it is also temporary: once Run is a kind of its own
// (roadmap §8 PR 4) the activity feed becomes a kube list and the fan-out here
// goes away.
//
// The curated model catalog is a bundle asset, not a call: it is compiled-in
// reference data with no tenant content, regenerated by
// `go run ./internal/gencatalog` and guarded by a Go test.
//
// The method surface is the same either way, so a view does not have to know
// which half it is calling.
//
// Tenant scope: the host pushes orgUUID/workspaceUUID on the RailgridContext, and
// those win. portalkit/tenant.ts's localStorage copy is the fallback for the
// (brief) window before the host has pushed a context.
//
// Every call — verb or object — goes through the host-owned transport
// (providerFetch), which injects the Bearer token; the X-Railgrid-Org /
// X-Railgrid-Workspace headers still ride on the few hub-proxied calls.

import type {
  Agent,
  AgentCreate,
  AgentPatch,
  Capabilities,
  Connection,
  ConnectionWrite,
  Credential,
  CredentialTestResult,
  CredentialWrite,
  InboxItem,
  RailgridContext,
  ModelInfo,
  RunDetail,
  RunSummary,
  Schedule,
  ScheduleCreate,
  SchedulePatch,
  SessionMeta,
  Toolset,
  ToolsetWrite,
  TranscriptMessage,
  Trigger,
  TriggerCreate,
  KubeRun,
  RunPhase,
  TriggerPatch,
  UsageBucket,
  UsagePoint,
  UsageResponse,
} from './types'

import { kubeVerbPath, type KubeResourceRef } from './portalkit/kube'
import { providerFetch, readTenant, serviceBase, tenantHeaders, type Tenant } from './portalkit/tenant'
import { AGENTS, CONNECTIONS, MODELCREDENTIALS, RUNS, Resources, SCHEDULES, TRIGGERS } from './resources'

export type { Tenant }
export { ResourceError } from './resources'

// SSEEvent is one parsed frame from any of the provider's event streams.
export interface SSEEvent<T = unknown> {
  id?: string
  event: string
  data: T
}

export interface RunPage {
  items: RunSummary[]
  nextCursor?: string
}

export interface RunFilter {
  agent?: string
  class?: string
  phase?: string
  trigger?: string
  session?: string
  parent?: string
  // since/until bound createdAt; both are RFC3339 (the API 400s on anything
  // else, so they are only ever built from Date.toISOString()).
  since?: string
  until?: string
  cursor?: string
  limit?: number
}

// ContextAuthority is the security boundary for a mounted provider. The
// workspace selects the data scope; userKey and token select the caller that
// is allowed to read it. A token rotation for the same known user still
// requires a fresh client/store, but does not require throwing away the
// user's route.
export interface ContextAuthority {
  usable: boolean
  tenantKey: string
  userKey: string | null
  token: string | null
}

// ApiError carries the HTTP status alongside the message so callers can tell a
// 404 (agent gone) from a 502 (upstream) without string-matching.
export class ApiError extends Error {
  readonly status: number
  constructor(status: number, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

export class ApiClient {
  private ctx: RailgridContext | null = null
  // The kcp half. It is handed the same context so a workspace switch moves
  // both halves at once.
  private readonly resources = new Resources()

  setContext(ctx: RailgridContext | null): void {
    this.ctx = ctx
    this.resources.setContext(ctx)
  }

  context(): RailgridContext | null {
    return this.ctx
  }

  // The host passes basePath as /ui/providers/agents; the two routes that are
  // not kcp API traffic — /oauth/providers and /mcp — live under the hub's
  // service-proxy path (portalkit/tenant.serviceBase rewrites the prefix). A
  // verb is never addressed this way: see verb().
  private url(path: string): string {
    return serviceBase(this.ctx?.basePath || '/ui/providers/agents') + path
  }

  // assetURL addresses a file in this bundle rather than the backend: the
  // bundle is served from basePath, which is where the hub's UI proxy mounts
  // it.
  private assetURL(path: string): string {
    return (this.ctx?.basePath || '/ui/providers/agents') + path
  }

  // cluster is the kcp logical-cluster ID of the active workspace. It is what
  // the data-plane grammar addresses, and it is the same value the kube half
  // uses — so there is exactly one answer to "which workspace is this?".
  private cluster(): string {
    return (this.ctx?.tenant || '').trim()
  }

  /**
   * verb builds the kube path of one data-plane verb — the custom subresource
   * `{resource}/{verb}` on the named object:
   *
   *   /clusters/{cluster}/apis/agents.railgrid.ai/v1alpha1/{resource}/{name}/{verb}[/{tail}][?query]
   *
   * It is fetched as-is: a kube path is rooted at the portal origin, and the
   * host transport injects the bearer. `name` is the object kcp authorizes
   * the verb on and the provider's gate checks visibility of, so it is never
   * a client-side filter — it is the subject. `tail` is raw; kubeVerbPath
   * encodes each segment.
   */
  private verb(ref: KubeResourceRef, name: string, verb: string, opts: { query?: Record<string, string | number | boolean | undefined> } = {}): string {
    const cluster = this.cluster()
    if (!cluster) throw new ApiError(400, 'no workspace selected')
    if (!name) throw new ApiError(400, `a ${ref.resource.replace(/s$/, '')} name is required`)
    return kubeVerbPath(cluster, ref, name, verb, opts)
  }

  /**
   * verbTail appends the one tail segment a verb takes (a session id, an inbox
   * item id) to a verb path, unencoded.
   *
   * kubeVerbPath's own `tail` option percent-encodes each segment, but the
   * provider's parser refuses a path that ARRIVED percent-encoded
   * (dataplane.ParseSubresourceRequest) and accepts exactly the segments Go's
   * url.PathEscape leaves untouched — which is where a session id such as
   * "schedule:daily" lives (":" is legal in a path segment; encoded as %3A it
   * would be refused). So the segment is checked here against that same rule
   * and sent as-is; anything else is refused with the answer the provider
   * would give.
   */
  private verbTail(path: string, tail: string): string {
    if (!tail || tail === '.' || tail === '..' || !VERB_TAIL_SEGMENT.test(tail)) {
      throw new ApiError(400, `${JSON.stringify(tail)} is not a valid path segment`)
    }
    return `${path}/${tail}`
  }

  // agentNames are the agents this caller can see. Every fan-out below is
  // bounded by it, which is also what bounds what the fan-out can reveal.
  private async agentNames(): Promise<string[]> {
    const agents = await this.resources.listAgents()
    return agents.map((a) => a.metadata.name).filter((n): n is string => !!n)
  }

  // inboxAgents remembers which agent an inbox item belongs to, so resolving
  // one by id alone can address the right object. Inbox items are Postgres-only
  // under the projection carve-out (see docs/agents-provider-architecture.md):
  // an inbox item is a pause in a run with exactly that run's lifetime, and a
  // second CR whose deletion semantics have to track the run's buys nothing a
  // tenant can authorize. So unlike runs, they have no object to list.
  private readonly inboxAgents = new Map<string, string>()

  private async agentForInboxItem(id: string): Promise<string> {
    const known = this.inboxAgents.get(id)
    if (known) return known
    await this.listInbox()
    const found = this.inboxAgents.get(id)
    if (!found) throw new ApiError(404, 'no such inbox item in this workspace')
    return found
  }

  // settleAll runs one request per agent and keeps the ones that answered. A
  // single agent that 403s (a grant the caller does not hold on that one agent)
  // must not blank the whole view; a failure that is not per-agent shows up on
  // every one of them and is rethrown.
  private async settleAll<T>(work: (agent: string) => Promise<T>): Promise<T[]> {
    const names = await this.agentNames()
    const settled = await Promise.allSettled(names.map(work))
    const values = settled.flatMap((r) => (r.status === 'fulfilled' ? [r.value] : []))
    if (!values.length && settled.length) {
      const first = settled.find((r) => r.status === 'rejected') as PromiseRejectedResult | undefined
      if (first) throw first.reason
    }
    return values
  }

  tenant(context: RailgridContext | null = this.ctx): Tenant {
    const stored = readTenant()
    // A host-supplied tenant is authoritative even when it explicitly clears
    // one or both fields. Falling back through null here could keep using a
    // stale localStorage workspace after the host has made the context
    // unusable.
    const hasContextTenant = !!context && ('orgUUID' in context || 'workspaceUUID' in context)
    return {
      orgUUID: hasContextTenant ? context?.orgUUID ?? null : stored.orgUUID,
      workspaceUUID: hasContextTenant ? context?.workspaceUUID ?? null : stored.workspaceUUID,
    }
  }

  hasWorkspace(): boolean {
    const t = this.tenant()
    return !!t.orgUUID && !!t.workspaceUUID
  }

  // tenantKey identifies the current workspace for change-detection (load dedupe).
  tenantKey(context: RailgridContext | null = this.ctx): string {
    const t = this.tenant(context)
    return `${t.orgUUID || ''}/${t.workspaceUUID || ''}`
  }

  contextAuthority(context: RailgridContext | null = this.ctx): ContextAuthority {
    const tenant = this.tenant(context)
    const user = context?.user as { sub?: unknown; userId?: unknown; email?: unknown } | null | undefined
    const userKey = [user?.sub, user?.userId, user?.email].find((value): value is string => typeof value === 'string' && value.length > 0) || null
    return {
      usable: !!context?.basePath && !!tenant.orgUUID && !!tenant.workspaceUUID,
      tenantKey: this.tenantKey(context),
      userKey,
      token: context?.token ?? null,
    }
  }

  // Every request goes through the host-owned fetch (portalkit providerFetch):
  // the host injects Authorization and the tenant scope, so this client never
  // handles the user's raw token. Older hosts without ctx.fetch fall back to
  // the global fetch plus ctx.token inside the helper.
  private fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
    return providerFetch(this.ctx)(input, init)
  }

  private headers(hasBody: boolean): Record<string, string> {
    const h = tenantHeaders({ json: hasBody })
    // Host context wins over the localStorage copy portalkit read.
    const t = this.tenant()
    if (t.orgUUID) h['X-Railgrid-Org'] = t.orgUUID
    else delete h['X-Railgrid-Org']
    if (t.workspaceUUID) h['X-Railgrid-Workspace'] = t.workspaceUUID
    else delete h['X-Railgrid-Workspace']
    return h
  }

  private async fail(r: Response): Promise<ApiError> {
    const body = (await r.json().catch(() => null)) as { message?: string; error?: { message?: string } } | null
    return new ApiError(r.status, body?.error?.message || body?.message || r.statusText || `HTTP ${r.status}`)
  }

  // get and send take a hub-proxied path (/oauth/providers) and rewrite it
  // under the service proxy; getVerb, sendVerb and listVerb take a kube path
  // from verb() and fetch it as-is.
  async get<T>(path: string): Promise<T> {
    return this.getURL(this.url(path))
  }

  async send<T>(method: string, path: string, body?: unknown, signal?: AbortSignal): Promise<T> {
    return this.sendURL(method, this.url(path), body, signal)
  }

  private getVerb<T>(path: string): Promise<T> {
    return this.getURL(path)
  }

  private sendVerb<T>(method: string, path: string, body?: unknown, signal?: AbortSignal): Promise<T> {
    return this.sendURL(method, path, body, signal)
  }

  private async getURL<T>(url: string): Promise<T> {
    const r = await this.fetch(url, { credentials: 'same-origin', headers: this.headers(false) })
    if (!r.ok) throw await this.fail(r)
    return r.json() as Promise<T>
  }

  private async sendURL<T>(method: string, url: string, body?: unknown, signal?: AbortSignal): Promise<T> {
    const r = await this.fetch(url, {
      method,
      credentials: 'same-origin',
      headers: this.headers(body !== undefined),
      body: body !== undefined ? JSON.stringify(body) : undefined,
      signal,
    })
    if (!r.ok) throw await this.fail(r)
    return (r.status === 204 ? (undefined as unknown) : await r.json()) as T
  }

  // listVerb unwraps the standard { items: [...] } list envelope a verb
  // answers with, tolerating a missing body.
  private async listVerb<T>(path: string): Promise<T[]> {
    const res = await this.getVerb<{ items?: T[] }>(path)
    return res.items || []
  }

  // ---- entities ------------------------------------------------------------

  // Objects: kcp. See resources.ts — the CRs are bound in the tenant's own
  // workspace, so the provider backend has no business relaying CRUD for them.
  listAgents = (): Promise<Agent[]> => this.resources.listAgents()
  createAgent = (body: AgentCreate): Promise<Agent> => this.resources.createAgent(body)
  patchAgent = (name: string, body: AgentPatch): Promise<Agent> => this.resources.patchAgent(name, body)
  deleteAgent = (name: string): Promise<void> => this.resources.deleteAgent(name)

  listSessions = (agent: string): Promise<SessionMeta[]> =>
    this.listVerb<SessionMeta>(this.verb(AGENTS, agent, 'sessions'))
  deleteSession = (agent: string, session: string): Promise<void> =>
    this.sendVerb('DELETE', this.verbTail(this.verb(AGENTS, agent, 'session'), session))
  listMessages = (agent: string, session: string, limit = 200): Promise<TranscriptMessage[]> =>
    this.listVerb<TranscriptMessage>(this.verb(AGENTS, agent, 'messages', { query: { session, limit } }))

  // Model credentials are ModelCredential objects in the tenant workspace,
  // written through kcp; the API key stays in the Secret each one points at.
  //
  // What stays on the backend is the live probe, because it needs the key to
  // reach the model endpoint and the browser must not hold a key long enough
  // to call a third party with it. Both probes are verbs on the CREDENTIAL:
  // `create` on modelcredentials/test is a grant about the thing being
  // probed, and — the reason the shape changed — a credential exists before
  // any agent does, so first-run works. They used to hang off an arbitrary
  // Agent, which meant an empty workspace could save a credential and then had
  // nothing to test it with.
  listCredentials = (): Promise<Credential[]> => this.resources.listCredentials()
  saveCredential = (body: CredentialWrite): Promise<Credential> => this.resources.saveCredential(body)
  deleteCredential = (name: string): Promise<void> => this.resources.deleteCredential(name)
  /**
   * testCredential runs one real chat round-trip against the saved credential.
   *
   * `model` overrides the model for THAT probe only — the endpoint and the key
   * still come from the saved object and its Secret. It exists so the editor
   * can verify the model a person just picked before "Save changes" writes it:
   * without it, the first thing that ever exercised a pick was the first agent
   * run, which is where a model the endpoint lists but will not chat on
   * surfaces as a 404 in someone's chat window.
   */
  testCredential = (name: string, model?: string): Promise<CredentialTestResult> =>
    this.sendVerb('POST', this.verb(MODELCREDENTIALS, name, 'test'), model ? { model } : undefined)
  /**
   * discoverCredential asks the endpoint what it serves. It also refreshes the
   * object's status.models, so the list a person just saw and the list the
   * object reports are the same one.
   */
  discoverCredential = (name: string): Promise<CredentialTestResult> =>
    this.sendVerb('POST', this.verb(MODELCREDENTIALS, name, 'discover'))

  // The curated catalog is compiled-in reference data — prices, context
  // windows, capabilities — with no tenant content, so it ships in the bundle
  // rather than over a route. providers/agents/api keeps it honest against
  // llm.Catalog().
  catalog = async (): Promise<ModelInfo[]> => {
    const r = await this.fetch(this.assetURL('/model-catalog.json'), { credentials: 'same-origin' })
    if (!r.ok) throw await this.fail(r)
    return (await r.json()) as ModelInfo[]
  }

  // usage is per-agent on the wire; the dashboard wants the workspace. Summing
  // the agents the caller can see is the only total that is honest about what
  // they are entitled to. Collections are normalized to arrays here rather than
  // guarded at every use site: Go marshals a nil slice as null, so an empty
  // workspace would otherwise fault the dashboard on its first render.
  usage = async (days: number): Promise<UsageResponse> => {
    const parts = await this.settleAll((agent) =>
      this.getVerb<UsageResponse>(this.verb(AGENTS, agent, 'usage', { query: { days } })),
    )
    return mergeUsage(days, parts)
  }

  listConnections = (): Promise<Connection[]> => this.resources.listConnections()
  // A connection may lean on an operator-configured OAuth app instead of the
  // user pasting client credentials. Which apps exist is a property of the
  // deployment, not of the workspace, so it is still a backend probe — read
  // once per create and handed to the writer.
  createConnection = async (body: ConnectionWrite): Promise<Connection> => {
    let platformApps: Record<string, boolean> = {}
    if ((body.auth ?? '').trim() === 'oauth') {
      platformApps = (await this.oauthProviders()).providers ?? {}
    }
    return this.resources.createConnection(body, platformApps)
  }
  patchConnection = (name: string, body: ConnectionWrite): Promise<Connection> =>
    this.resources.patchConnection(name, body)
  deleteConnection = (name: string): Promise<void> => this.resources.deleteConnection(name)
  testConnection = (name: string): Promise<unknown> =>
    this.sendVerb('POST', this.verb(CONNECTIONS, name, 'test'))
  enableInbound = (name: string): Promise<{ webhookURL: string; registered: boolean; note: string }> =>
    this.sendVerb('POST', this.verb(CONNECTIONS, name, 'enable-inbound'), { publicBaseURL: location.origin })
  oauthAuthorize = (name: string): Promise<{ authorizeURL: string }> =>
    this.sendVerb('POST', this.verb(CONNECTIONS, name, 'authorize'), { publicBaseURL: location.origin })
  // Which platform-wide OAuth apps the operator configured is a fact about the
  // deployment with no object to hang a verb on, so it lives with the rest of
  // the browser OAuth flow under /oauth/.
  oauthProviders = (): Promise<{ providers?: Record<string, boolean> }> => this.get('/oauth/providers')

  // What the tenant's enabled providers let an agent reach, read off the
  // workspace's own MCPServer rather than probed through the backend.
  capabilities = async (): Promise<Capabilities> => {
    const c = await this.resources.capabilities()
    return { ...c, providers: c.providers ?? [] }
  }

  listToolsets = (): Promise<Toolset[]> => this.resources.listToolsets()
  createToolset = (body: ToolsetWrite): Promise<Toolset> => this.resources.createToolset(body)
  patchToolset = (name: string, body: ToolsetWrite): Promise<Toolset> => this.resources.patchToolset(name, body)
  deleteToolset = (name: string): Promise<void> => this.resources.deleteToolset(name)

  listSchedules = (): Promise<Schedule[]> => this.resources.listSchedules()
  createSchedule = (body: ScheduleCreate): Promise<Schedule> => this.resources.createSchedule(body)
  patchSchedule = (name: string, body: SchedulePatch): Promise<Schedule> => this.resources.patchSchedule(name, body)
  deleteSchedule = (name: string): Promise<void> => this.resources.deleteSchedule(name)
  // Run-now is asynchronous: 202 + the runID to follow in Activity.
  runSchedule = (name: string): Promise<{ runID: string }> =>
    this.sendVerb('POST', this.verb(SCHEDULES, name, 'run'))

  listTriggers = (): Promise<Trigger[]> => this.resources.listTriggers()
  createTrigger = (body: TriggerCreate): Promise<Trigger> => this.resources.createTrigger(body)
  patchTrigger = (name: string, body: TriggerPatch): Promise<Trigger> => this.resources.patchTrigger(name, body)
  deleteTrigger = (name: string): Promise<void> => this.resources.deleteTrigger(name)
  runTrigger = (name: string): Promise<{ runID: string }> =>
    this.sendVerb('POST', this.verb(TRIGGERS, name, 'run'))

  listInbox = async (): Promise<InboxItem[]> => {
    const pages = await this.settleAll((agent) =>
      this.listVerb<InboxItem>(this.verb(AGENTS, agent, 'inbox')),
    )
    const items = pages.flat()
    for (const item of items) if (item.id && item.agentName) this.inboxAgents.set(item.id, item.agentName)
    return items.sort(byNewest)
  }
  resolveInbox = async (id: string, decision: 'approve' | 'deny' | 'answer', response?: string): Promise<InboxItem> => {
    const agent = await this.agentForInboxItem(id)
    return this.sendVerb('POST', this.verbTail(this.verb(AGENTS, agent, 'inbox-resolve'), id), { decision, response })
  }

  // Runs are objects. Listing them, reading one and deleting one are kube
  // calls; what stays on the backend is the half that is not on the object —
  // the Postgres-backed trace — plus the two things that need the executor.
  listRuns = async (f: RunFilter = {}): Promise<RunPage> => {
    const objects = await this.resources.listRuns(f.agent)
    let items = objects.map(runSummaryFromObject).sort(byNewest)
    if (f.phase) items = items.filter((r) => r.phase === f.phase)
    if (f.trigger) items = items.filter((r) => r.trigger === f.trigger)
    if (f.class) items = items.filter((r) => r.class === f.class)
    if (f.session) items = items.filter((r) => r.sessionID === f.session)
    if (f.parent) items = items.filter((r) => r.parentRunID === f.parent)
    // since/until bound createdAt; both are RFC3339, so a string compare is a
    // chronological one.
    if (f.since) items = items.filter((r) => r.createdAt >= (f.since as string))
    if (f.until) items = items.filter((r) => r.createdAt <= (f.until as string))
    // The cursor is gone with the backend list: a kube list pages by
    // `continue`, listRuns walks it to exhaustion, and pretending to hand back
    // an opaque cursor the caller cannot resume would be a lie.
    return { items: f.limit ? items.slice(0, f.limit) : items }
  }

  getRun = async (id: string): Promise<RunDetail> => {
    // Two halves, one shape. The object is authoritative for phase, timings and
    // cost; the trace verb supplies what is not on it — the answer, the step
    // trace, the pending-approval disclosure and the children.
    const object = await this.resources.getRun(id)
    const summary = runSummaryFromObject(object)
    let trace: Partial<RunDetail> = {}
    try {
      trace = await this.getVerb<RunDetail>(this.verb(RUNS, id, 'trace'))
    } catch (e) {
      // A run whose rows have been purged, or a caller without the trace grant,
      // still gets the object. An empty trace is a true statement about what we
      // can see; failing the whole read would hide the run itself.
      if ((e as ApiError).status !== 404 && (e as ApiError).status !== 403) throw e
    }
    return {
      ...summary,
      ...trace,
      // The object wins on every field it owns: the trace is a snapshot of
      // Postgres and may be a transition behind.
      ...summary,
      input: trace.input,
      output: trace.output,
      sources: trace.sources,
      pending: trace.pending,
      steps: trace.steps ?? [],
      children: trace.children ?? [],
    }
  }

  cancelRun = (id: string): Promise<{ id: string; cancelling: boolean }> =>
    this.sendVerb('POST', this.verb(RUNS, id, 'cancel'))

  /** waitRun blocks until the run settles. For a caller with no watch to hold. */
  waitRun = (id: string, timeoutSeconds = 60): Promise<RunDetail> =>
    this.getVerb<RunDetail>(this.verb(RUNS, id, 'wait', { query: { timeoutSeconds } }))

  deleteRun = (id: string): Promise<void> => this.resources.deleteRun(id)

  // ---- streams -------------------------------------------------------------

  // chatStream POSTs a message and yields parsed SSE frames as they arrive. The
  // caller drives the loop and applies deltas/tool events/errors. `signal`
  // aborts the fetch so a Stop button can drop the stream immediately. The
  // stream rides the kube path like every other verb: kcp's reverse proxy
  // flushes as the provider writes.
  async *chatStream(agent: string, message: string, sessionID: string, signal?: AbortSignal): AsyncGenerator<SSEEvent> {
    const r = await this.fetch(this.verb(AGENTS, agent, 'chat'), {
      method: 'POST',
      credentials: 'same-origin',
      headers: this.headers(true),
      body: JSON.stringify({ message, sessionID: sessionID || undefined }),
      signal,
    })
    if (!r.ok || !r.body) throw await this.fail(r)
    yield* readSSE(r.body, signal)
  }

  // eventStream follows run and inbox activity for every agent the caller can
  // see, as one merged stream.
  //
  // It is a plain fetch rather than EventSource because EventSource cannot send
  // the Authorization header the kcp front door requires. onOpen fires as soon
  // as any stream's response headers are in, which is the real liveness signal
  // — the server may legitimately send no parsable event for minutes.
  //
  // One connection per agent is the cost of the grammar addressing an object:
  // the caller was authorized to watch THIS agent, not the workspace. It is
  // capped, and it collapses back to a single subscription once Run is a kind
  // and the portal can watch it directly.
  async *eventStream(signal: AbortSignal, onOpen?: () => void): AsyncGenerator<SSEEvent> {
    const names = (await this.agentNames()).slice(0, MAX_EVENT_STREAMS)
    if (!names.length) {
      // Nothing to watch is not the same as nothing working: report live and
      // park until the caller aborts, so the UI does not show "reconnecting".
      onOpen?.()
      await new Promise<void>((resolve) => {
        if (signal.aborted) return resolve()
        signal.addEventListener('abort', () => resolve(), { once: true })
      })
      return
    }

    const queue: SSEEvent[] = []
    let wake: (() => void) | null = null
    const nudge = () => {
      const resume = wake
      wake = null
      resume?.()
    }
    let open = names.length
    let failure: unknown = null

    for (const name of names) {
      void (async () => {
        try {
          const r = await this.fetch(this.verb(AGENTS, name, 'events'), {
            credentials: 'same-origin',
            headers: this.headers(false),
            signal,
          })
          if (!r.ok || !r.body) throw await this.fail(r)
          onOpen?.()
          for await (const ev of readSSE(r.body, signal)) {
            queue.push(ev)
            nudge()
          }
        } catch (e) {
          failure ??= e
        } finally {
          open--
          nudge()
        }
      })()
    }

    while (open > 0 || queue.length) {
      if (queue.length) {
        yield queue.shift() as SSEEvent
        continue
      }
      await new Promise<void>((resolve) => {
        wake = resolve
      })
    }
    // Every stream ended. A clean end means the caller aborted; anything else
    // is a drop the store should back off and retry on.
    if (failure && !signal.aborted) throw failure
  }
}

// VERB_TAIL_SEGMENT is the set of characters Go's url.PathEscape leaves as they
// are in a path segment: RFC 3986 unreserved plus the sub-delims and ":" / "@"
// a segment may carry. It is the provider's rule for a tail segment
// (provider-sdk/dataplane validSegment), mirrored so the client refuses what
// the server would.
const VERB_TAIL_SEGMENT = /^[A-Za-z0-9\-._~!$&'()*+:=@]+$/

// MAX_EVENT_STREAMS caps the fan-out. A workspace with more agents than this
// polls for the rest, which is what the store already does whenever the stream
// is down.
const MAX_EVENT_STREAMS = 12

// INTERACTIVE_TRIGGERS mirrors api/toolset.go's isInteractive. `class` is a
// derived field the Activity filter uses; it is derived here rather than stored
// on the Run so there is one taxonomy of triggers, not two.
const INTERACTIVE_TRIGGERS = new Set(['chat', 'channel'])

/**
 * runSummaryFromObject projects a Run object onto the shape the views render.
 *
 * The views were written against the backend's runSummary JSON and there is no
 * reason to rewrite them: what changed is where the facts come from, not what
 * they are. Fields the object does not carry (attempt, hasOutput) are absent
 * rather than invented — a zero that means "unknown" is worse than nothing.
 */
export function runSummaryFromObject(object: KubeRun): RunSummary {
  // Every branch is optional-guarded on purpose: this reads an API object, and
  // an object written by an older provider (or mid-creation, before its status
  // exists) must render as a run with unknowns rather than fault the feed.
  const meta = object.metadata ?? ({} as KubeRun['metadata'])
  const spec = object.spec ?? ({} as KubeRun['spec'])
  const status = object.status ?? {}
  const usage = status.usage ?? {}
  return {
    id: meta.name || '',
    agent: spec.agentRef || '',
    sessionID: spec.sessionID,
    trigger: spec.trigger || '',
    class: INTERACTIVE_TRIGGERS.has(spec.trigger || '') ? 'interactive' : 'background',
    parentRunID: spec.parentRunRef,
    phase: (status.phase || 'Pending') as RunPhase,
    inputPreview: spec.inputPreview,
    message: status.message,
    inputTokens: usage.inputTokens ?? 0,
    outputTokens: usage.outputTokens ?? 0,
    usdMicros: usage.usdMicros ?? 0,
    // creationTimestamp is when the object was created, which is when the run
    // was accepted — the same instant the store's createdAt records.
    createdAt: meta.creationTimestamp || status.startedAt || '',
    startedAt: status.startedAt,
    finishedAt: status.finishedAt,
    durationMS: usage.durationMS,
    workedDurationMS: usage.workedDurationMS,
  }
}

// byNewest orders a merged feed. createdAt is RFC3339 from the server, so a
// lexicographic compare is a chronological one; the id breaks ties so the order
// is stable across refreshes.
function byNewest<T extends { id: string; createdAt: string }>(a: T, b: T): number {
  if (a.createdAt !== b.createdAt) return a.createdAt < b.createdAt ? 1 : -1
  return a.id < b.id ? 1 : -1
}

// mergeUsage sums the per-agent rollups into the workspace view the dashboard
// renders. Latency percentiles cannot be summed — a percentile of percentiles
// is not a percentile — so the total takes the worst agent's, which is the only
// statement that stays true of the whole workspace.
function mergeUsage(days: number, parts: UsageResponse[]): UsageResponse {
  const total: UsageBucket = { key: 'total', runs: 0, errors: 0, inputTokens: 0, outputTokens: 0, usdMicros: 0, latencyP50MS: 0, latencyP95MS: 0 }
  const byAgent: UsageBucket[] = []
  const byModel = new Map<string, UsageBucket>()
  const series = new Map<string, UsagePoint>()

  for (const part of parts) {
    total.runs += part.total?.runs ?? 0
    total.errors += part.total?.errors ?? 0
    total.inputTokens += part.total?.inputTokens ?? 0
    total.outputTokens += part.total?.outputTokens ?? 0
    total.usdMicros += part.total?.usdMicros ?? 0
    total.latencyP50MS = Math.max(total.latencyP50MS, part.total?.latencyP50MS ?? 0)
    total.latencyP95MS = Math.max(total.latencyP95MS, part.total?.latencyP95MS ?? 0)
    byAgent.push(...(part.byAgent ?? []))
    for (const bucket of part.byModel ?? []) {
      const existing = byModel.get(bucket.key)
      if (!existing) {
        byModel.set(bucket.key, { ...bucket })
        continue
      }
      existing.runs += bucket.runs
      existing.errors += bucket.errors
      existing.inputTokens += bucket.inputTokens
      existing.outputTokens += bucket.outputTokens
      existing.usdMicros += bucket.usdMicros
      existing.latencyP50MS = Math.max(existing.latencyP50MS, bucket.latencyP50MS)
      existing.latencyP95MS = Math.max(existing.latencyP95MS, bucket.latencyP95MS)
    }
    for (const point of part.series ?? []) {
      const existing = series.get(point.date)
      if (!existing) {
        series.set(point.date, { ...point })
        continue
      }
      existing.runs += point.runs
      existing.inputTokens += point.inputTokens
      existing.outputTokens += point.outputTokens
      existing.usdMicros += point.usdMicros
    }
  }

  const bySpend = (a: UsageBucket, b: UsageBucket) =>
    b.usdMicros - a.usdMicros || b.runs - a.runs || a.key.localeCompare(b.key)
  return {
    windowDays: days,
    total,
    byAgent: byAgent.sort(bySpend),
    byModel: [...byModel.values()].sort(bySpend),
    series: [...series.values()].sort((a, b) => a.date.localeCompare(b.date)),
  }
}


// readSSE turns a byte stream into parsed SSE events.
//
// Framing follows the spec rather than the previous implementation's
// `split('\n\n')` + `data.trim()` concatenation: frames end on a blank line in
// any newline flavour, and multi-line `data:` fields join with '\n' (a JSON
// payload pretty-printed across lines would otherwise be silently corrupted).
export async function* readSSE(body: ReadableStream<Uint8Array>, signal?: AbortSignal): AsyncGenerator<SSEEvent> {
  const reader = body.getReader()
  const dec = new TextDecoder()
  let buf = ''
  try {
    for (;;) {
      const { done, value } = await reader.read()
      if (done) break
      buf += dec.decode(value, { stream: true })
      // Normalize CRLF / lone CR so a single split rule covers every flavour.
      buf = buf.replace(/\r\n|\r/g, '\n')
      let idx: number
      while ((idx = buf.indexOf('\n\n')) !== -1) {
        const frame = buf.slice(0, idx)
        buf = buf.slice(idx + 2)
        const ev = parseSSEFrame(frame)
        if (ev) yield ev
      }
      if (signal?.aborted) break
    }
  } finally {
    reader.cancel().catch(() => undefined)
  }
}

// parseSSEFrame parses one frame's field lines. Comment lines (": keepalive")
// and frames without a data field yield null.
export function parseSSEFrame(frame: string): SSEEvent | null {
  let event = 'message'
  let id: string | undefined
  const dataLines: string[] = []
  for (const line of frame.split('\n')) {
    if (!line || line.startsWith(':')) continue
    const colon = line.indexOf(':')
    const field = colon === -1 ? line : line.slice(0, colon)
    // A single leading space after the colon is part of the framing, not data.
    let value = colon === -1 ? '' : line.slice(colon + 1)
    if (value.startsWith(' ')) value = value.slice(1)
    if (field === 'event') event = value
    else if (field === 'data') dataLines.push(value)
    else if (field === 'id') id = value
  }
  if (!dataLines.length) return null
  const raw = dataLines.join('\n')
  try {
    return { id, event, data: JSON.parse(raw) }
  } catch {
    return { id, event, data: raw }
  }
}
