//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntry) DeepCopyInto(out *CatalogEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntry.
func (in *CatalogEntry) DeepCopy() *CatalogEntry {
	if in == nil {
		return nil
	}
	out := new(CatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntryList) DeepCopyInto(out *CatalogEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntryList.
func (in *CatalogEntryList) DeepCopy() *CatalogEntryList {
	if in == nil {
		return nil
	}
	out := new(CatalogEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntrySpec) DeepCopyInto(out *CatalogEntrySpec) {
	*out = *in
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(ProviderExport)
		(*in).DeepCopyInto(*out)
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]ProviderRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Serving != nil {
		in, out := &in.Serving, &out.Serving
		*out = new(ProviderServing)
		(*in).DeepCopyInto(*out)
	}
	if in.Hub != nil {
		in, out := &in.Hub, &out.Hub
		*out = new(ProviderHub)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntrySpec.
func (in *CatalogEntrySpec) DeepCopy() *CatalogEntrySpec {
	if in == nil {
		return nil
	}
	out := new(CatalogEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntryStatus) DeepCopyInto(out *CatalogEntryStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ProviderEndpoints)
		**out = **in
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsRotatedAt != nil {
		in, out := &in.CredentialsRotatedAt, &out.CredentialsRotatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ProviderUIStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntryStatus.
func (in *CatalogEntryStatus) DeepCopy() *CatalogEntryStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogEntryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAction) DeepCopyInto(out *ProviderAction) {
	*out = *in
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	out.Limits = in.Limits
	out.Consent = in.Consent
	if in.Deprecation != nil {
		in, out := &in.Deprecation, &out.Deprecation
		*out = new(ProviderActionDeprecation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAction.
func (in *ProviderAction) DeepCopy() *ProviderAction {
	if in == nil {
		return nil
	}
	out := new(ProviderAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionConsent) DeepCopyInto(out *ProviderActionConsent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionConsent.
func (in *ProviderActionConsent) DeepCopy() *ProviderActionConsent {
	if in == nil {
		return nil
	}
	out := new(ProviderActionConsent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionDeprecation) DeepCopyInto(out *ProviderActionDeprecation) {
	*out = *in
	if in.Sunset != nil {
		in, out := &in.Sunset, &out.Sunset
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionDeprecation.
func (in *ProviderActionDeprecation) DeepCopy() *ProviderActionDeprecation {
	if in == nil {
		return nil
	}
	out := new(ProviderActionDeprecation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionLimits) DeepCopyInto(out *ProviderActionLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionLimits.
func (in *ProviderActionLimits) DeepCopy() *ProviderActionLimits {
	if in == nil {
		return nil
	}
	out := new(ProviderActionLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAssistantSkillResource) DeepCopyInto(out *ProviderAssistantSkillResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAssistantSkillResource.
func (in *ProviderAssistantSkillResource) DeepCopy() *ProviderAssistantSkillResource {
	if in == nil {
		return nil
	}
	out := new(ProviderAssistantSkillResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAssistantSkillSpec) DeepCopyInto(out *ProviderAssistantSkillSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ProviderAssistantSkillResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAssistantSkillSpec.
func (in *ProviderAssistantSkillSpec) DeepCopy() *ProviderAssistantSkillSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAssistantSkillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderBackend) DeepCopyInto(out *ProviderBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderBackend.
func (in *ProviderBackend) DeepCopy() *ProviderBackend {
	if in == nil {
		return nil
	}
	out := new(ProviderBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCoordinate) DeepCopyInto(out *ProviderCoordinate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCoordinate.
func (in *ProviderCoordinate) DeepCopy() *ProviderCoordinate {
	if in == nil {
		return nil
	}
	out := new(ProviderCoordinate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderEndpoints) DeepCopyInto(out *ProviderEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderEndpoints.
func (in *ProviderEndpoints) DeepCopy() *ProviderEndpoints {
	if in == nil {
		return nil
	}
	out := new(ProviderEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderExport) DeepCopyInto(out *ProviderExport) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ProviderExportResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderExport.
func (in *ProviderExport) DeepCopy() *ProviderExport {
	if in == nil {
		return nil
	}
	out := new(ProviderExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderExportResource) DeepCopyInto(out *ProviderExportResource) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]ProviderVerb, len(*in))
		copy(*out, *in)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ProviderAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderExportResource.
func (in *ProviderExportResource) DeepCopy() *ProviderExportResource {
	if in == nil {
		return nil
	}
	out := new(ProviderExportResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderHub) DeepCopyInto(out *ProviderHub) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]ProviderHubAccess, len(*in))
		copy(*out, *in)
	}
	if in.AssistantSkills != nil {
		in, out := &in.AssistantSkills, &out.AssistantSkills
		*out = make([]ProviderAssistantSkillSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderHub.
func (in *ProviderHub) DeepCopy() *ProviderHub {
	if in == nil {
		return nil
	}
	out := new(ProviderHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderHubAccess) DeepCopyInto(out *ProviderHubAccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderHubAccess.
func (in *ProviderHubAccess) DeepCopy() *ProviderHubAccess {
	if in == nil {
		return nil
	}
	out := new(ProviderHubAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderLabelSelector) DeepCopyInto(out *ProviderLabelSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderLabelSelector.
func (in *ProviderLabelSelector) DeepCopy() *ProviderLabelSelector {
	if in == nil {
		return nil
	}
	out := new(ProviderLabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderNavChild) DeepCopyInto(out *ProviderNavChild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderNavChild.
func (in *ProviderNavChild) DeepCopy() *ProviderNavChild {
	if in == nil {
		return nil
	}
	out := new(ProviderNavChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRequiredResource) DeepCopyInto(out *ProviderRequiredResource) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]ProviderRequiredVerb, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ProviderLabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRequiredResource.
func (in *ProviderRequiredResource) DeepCopy() *ProviderRequiredResource {
	if in == nil {
		return nil
	}
	out := new(ProviderRequiredResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRequirement) DeepCopyInto(out *ProviderRequirement) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ProviderRequiredResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRequirement.
func (in *ProviderRequirement) DeepCopy() *ProviderRequirement {
	if in == nil {
		return nil
	}
	out := new(ProviderRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSelfHosting) DeepCopyInto(out *ProviderSelfHosting) {
	*out = *in
	if in.Chart != nil {
		in, out := &in.Chart, &out.Chart
		*out = new(ProviderSelfHostingChart)
		**out = **in
	}
	if in.RequiredValues != nil {
		in, out := &in.RequiredValues, &out.RequiredValues
		*out = make([]ProviderSelfHostingValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSelfHosting.
func (in *ProviderSelfHosting) DeepCopy() *ProviderSelfHosting {
	if in == nil {
		return nil
	}
	out := new(ProviderSelfHosting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSelfHostingChart) DeepCopyInto(out *ProviderSelfHostingChart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSelfHostingChart.
func (in *ProviderSelfHostingChart) DeepCopy() *ProviderSelfHostingChart {
	if in == nil {
		return nil
	}
	out := new(ProviderSelfHostingChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSelfHostingValue) DeepCopyInto(out *ProviderSelfHostingValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSelfHostingValue.
func (in *ProviderSelfHostingValue) DeepCopy() *ProviderSelfHostingValue {
	if in == nil {
		return nil
	}
	out := new(ProviderSelfHostingValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderServing) DeepCopyInto(out *ProviderServing) {
	*out = *in
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ProviderUI)
		(*in).DeepCopyInto(*out)
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(ProviderBackend)
		**out = **in
	}
	if in.SelfHosting != nil {
		in, out := &in.SelfHosting, &out.SelfHosting
		*out = new(ProviderSelfHosting)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderServing.
func (in *ProviderServing) DeepCopy() *ProviderServing {
	if in == nil {
		return nil
	}
	out := new(ProviderServing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderUI) DeepCopyInto(out *ProviderUI) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ProviderNavChild, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderUI.
func (in *ProviderUI) DeepCopy() *ProviderUI {
	if in == nil {
		return nil
	}
	out := new(ProviderUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderUIStatus) DeepCopyInto(out *ProviderUIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderUIStatus.
func (in *ProviderUIStatus) DeepCopy() *ProviderUIStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderUIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVerb) DeepCopyInto(out *ProviderVerb) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVerb.
func (in *ProviderVerb) DeepCopy() *ProviderVerb {
	if in == nil {
		return nil
	}
	out := new(ProviderVerb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredCoordinate) DeepCopyInto(out *RequiredCoordinate) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]ProviderRequiredVerb, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ProviderLabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredCoordinate.
func (in *RequiredCoordinate) DeepCopy() *RequiredCoordinate {
	if in == nil {
		return nil
	}
	out := new(RequiredCoordinate)
	in.DeepCopyInto(out)
	return out
}
