//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntry) DeepCopyInto(out *CatalogEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntry.
func (in *CatalogEntry) DeepCopy() *CatalogEntry {
	if in == nil {
		return nil
	}
	out := new(CatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntryList) DeepCopyInto(out *CatalogEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntryList.
func (in *CatalogEntryList) DeepCopy() *CatalogEntryList {
	if in == nil {
		return nil
	}
	out := new(CatalogEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntrySpec) DeepCopyInto(out *CatalogEntrySpec) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]ProviderDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ProviderUI)
		(*in).DeepCopyInto(*out)
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(ProviderBackend)
		**out = **in
	}
	if in.APIExport != nil {
		in, out := &in.APIExport, &out.APIExport
		*out = new(ProviderAPIExport)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfHosting != nil {
		in, out := &in.SelfHosting, &out.SelfHosting
		*out = new(ProviderSelfHosting)
		(*in).DeepCopyInto(*out)
	}
	if in.HubAccess != nil {
		in, out := &in.HubAccess, &out.HubAccess
		*out = make([]ProviderHubAccess, len(*in))
		copy(*out, *in)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ProviderActionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataPlane != nil {
		in, out := &in.DataPlane, &out.DataPlane
		*out = new(ProviderDataPlane)
		(*in).DeepCopyInto(*out)
	}
	if in.AssistantSkills != nil {
		in, out := &in.AssistantSkills, &out.AssistantSkills
		*out = make([]ProviderAssistantSkillSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntrySpec.
func (in *CatalogEntrySpec) DeepCopy() *CatalogEntrySpec {
	if in == nil {
		return nil
	}
	out := new(CatalogEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogEntryStatus) DeepCopyInto(out *CatalogEntryStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ProviderEndpoints)
		**out = **in
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsRotatedAt != nil {
		in, out := &in.CredentialsRotatedAt, &out.CredentialsRotatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ProviderUIStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogEntryStatus.
func (in *CatalogEntryStatus) DeepCopy() *CatalogEntryStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogEntryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAPIExport) DeepCopyInto(out *ProviderAPIExport) {
	*out = *in
	if in.PermissionClaims != nil {
		in, out := &in.PermissionClaims, &out.PermissionClaims
		*out = make([]ProviderPermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAPIExport.
func (in *ProviderAPIExport) DeepCopy() *ProviderAPIExport {
	if in == nil {
		return nil
	}
	out := new(ProviderAPIExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionBoundResource) DeepCopyInto(out *ProviderActionBoundResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionBoundResource.
func (in *ProviderActionBoundResource) DeepCopy() *ProviderActionBoundResource {
	if in == nil {
		return nil
	}
	out := new(ProviderActionBoundResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionConsent) DeepCopyInto(out *ProviderActionConsent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionConsent.
func (in *ProviderActionConsent) DeepCopy() *ProviderActionConsent {
	if in == nil {
		return nil
	}
	out := new(ProviderActionConsent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionDeprecation) DeepCopyInto(out *ProviderActionDeprecation) {
	*out = *in
	if in.Sunset != nil {
		in, out := &in.Sunset, &out.Sunset
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionDeprecation.
func (in *ProviderActionDeprecation) DeepCopy() *ProviderActionDeprecation {
	if in == nil {
		return nil
	}
	out := new(ProviderActionDeprecation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionLimits) DeepCopyInto(out *ProviderActionLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionLimits.
func (in *ProviderActionLimits) DeepCopy() *ProviderActionLimits {
	if in == nil {
		return nil
	}
	out := new(ProviderActionLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderActionSpec) DeepCopyInto(out *ProviderActionSpec) {
	*out = *in
	out.BoundResource = in.BoundResource
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	out.Limits = in.Limits
	out.Consent = in.Consent
	if in.Deprecation != nil {
		in, out := &in.Deprecation, &out.Deprecation
		*out = new(ProviderActionDeprecation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderActionSpec.
func (in *ProviderActionSpec) DeepCopy() *ProviderActionSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAssistantSkillResource) DeepCopyInto(out *ProviderAssistantSkillResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAssistantSkillResource.
func (in *ProviderAssistantSkillResource) DeepCopy() *ProviderAssistantSkillResource {
	if in == nil {
		return nil
	}
	out := new(ProviderAssistantSkillResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAssistantSkillSpec) DeepCopyInto(out *ProviderAssistantSkillSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ProviderAssistantSkillResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAssistantSkillSpec.
func (in *ProviderAssistantSkillSpec) DeepCopy() *ProviderAssistantSkillSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAssistantSkillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderBackend) DeepCopyInto(out *ProviderBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderBackend.
func (in *ProviderBackend) DeepCopy() *ProviderBackend {
	if in == nil {
		return nil
	}
	out := new(ProviderBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderComposition) DeepCopyInto(out *ProviderComposition) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]ProviderCompositionVerb, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderComposition.
func (in *ProviderComposition) DeepCopy() *ProviderComposition {
	if in == nil {
		return nil
	}
	out := new(ProviderComposition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderDataPlane) DeepCopyInto(out *ProviderDataPlane) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]ProviderDataPlaneVerb, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderDataPlane.
func (in *ProviderDataPlane) DeepCopy() *ProviderDataPlane {
	if in == nil {
		return nil
	}
	out := new(ProviderDataPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderDataPlaneVerb) DeepCopyInto(out *ProviderDataPlaneVerb) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderDataPlaneVerb.
func (in *ProviderDataPlaneVerb) DeepCopy() *ProviderDataPlaneVerb {
	if in == nil {
		return nil
	}
	out := new(ProviderDataPlaneVerb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderDependency) DeepCopyInto(out *ProviderDependency) {
	*out = *in
	if in.Composes != nil {
		in, out := &in.Composes, &out.Composes
		*out = make([]ProviderComposition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderDependency.
func (in *ProviderDependency) DeepCopy() *ProviderDependency {
	if in == nil {
		return nil
	}
	out := new(ProviderDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderEndpoints) DeepCopyInto(out *ProviderEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderEndpoints.
func (in *ProviderEndpoints) DeepCopy() *ProviderEndpoints {
	if in == nil {
		return nil
	}
	out := new(ProviderEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderHubAccess) DeepCopyInto(out *ProviderHubAccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderHubAccess.
func (in *ProviderHubAccess) DeepCopy() *ProviderHubAccess {
	if in == nil {
		return nil
	}
	out := new(ProviderHubAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderNavChild) DeepCopyInto(out *ProviderNavChild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderNavChild.
func (in *ProviderNavChild) DeepCopy() *ProviderNavChild {
	if in == nil {
		return nil
	}
	out := new(ProviderNavChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPermissionClaim) DeepCopyInto(out *ProviderPermissionClaim) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ProviderPermissionClaimSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPermissionClaim.
func (in *ProviderPermissionClaim) DeepCopy() *ProviderPermissionClaim {
	if in == nil {
		return nil
	}
	out := new(ProviderPermissionClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPermissionClaimSelector) DeepCopyInto(out *ProviderPermissionClaimSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPermissionClaimSelector.
func (in *ProviderPermissionClaimSelector) DeepCopy() *ProviderPermissionClaimSelector {
	if in == nil {
		return nil
	}
	out := new(ProviderPermissionClaimSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSelfHosting) DeepCopyInto(out *ProviderSelfHosting) {
	*out = *in
	if in.Chart != nil {
		in, out := &in.Chart, &out.Chart
		*out = new(ProviderSelfHostingChart)
		**out = **in
	}
	if in.RequiredValues != nil {
		in, out := &in.RequiredValues, &out.RequiredValues
		*out = make([]ProviderSelfHostingValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSelfHosting.
func (in *ProviderSelfHosting) DeepCopy() *ProviderSelfHosting {
	if in == nil {
		return nil
	}
	out := new(ProviderSelfHosting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSelfHostingChart) DeepCopyInto(out *ProviderSelfHostingChart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSelfHostingChart.
func (in *ProviderSelfHostingChart) DeepCopy() *ProviderSelfHostingChart {
	if in == nil {
		return nil
	}
	out := new(ProviderSelfHostingChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSelfHostingValue) DeepCopyInto(out *ProviderSelfHostingValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSelfHostingValue.
func (in *ProviderSelfHostingValue) DeepCopy() *ProviderSelfHostingValue {
	if in == nil {
		return nil
	}
	out := new(ProviderSelfHostingValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderUI) DeepCopyInto(out *ProviderUI) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ProviderNavChild, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderUI.
func (in *ProviderUI) DeepCopy() *ProviderUI {
	if in == nil {
		return nil
	}
	out := new(ProviderUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderUIStatus) DeepCopyInto(out *ProviderUIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderUIStatus.
func (in *ProviderUIStatus) DeepCopy() *ProviderUIStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderUIStatus)
	in.DeepCopyInto(out)
	return out
}
