/*
Copyright 2026 The Railgrid Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package crossprovider

// The requirement: what App Studio declares it does to a dependency's objects.
//
// The CatalogEntry declares it as `spec.requires` (manifest.yaml and the
// chart's copy, identically) — ONE list, keyed by API group, covering both the
// dependency edge the hub orders Enable by and the access itself. That one declaration is the permission
// claim on App Studio's own APIExport — identity-agnostic, generated by
// provider-sdk/apiexportgen, admitted by the platform's PermissionClaimPolicy
// and accepted by the tenant at Enable — under which the reconcilers read,
// watch and write the composed kinds THROUGH this export's virtual workspace,
// as the provider. kcp resolves the claim per consumer workspace, so each
// workspace is served the copy of the dependency IT bound. No identity is
// minted for any of it; what the Project identity still carries is what the
// dependency's data plane checks when a project calls a verb on one of its
// objects (controller/project/identity.go).
//
// See docs/app-studio-runtime-decoupling.md.

const (
	// InfrastructureAPIGroup / CodeAPIGroup are the dependency groups. They are
	// FOREIGN groups: nothing here is a claim on them, and every object verb is
	// name-scoped.
	InfrastructureAPIGroup = "infrastructure.railgrid.ai"
	CodeAPIGroup           = "code.railgrid.ai"

	// InstancesResource is the infrastructure provider's one instance kind.
	// A Project binding records a per-template resource name that resolves to
	// it; a binding naming anything else is not part of the declared
	// composition and gets a plain foreign read instead.
	InstancesResource = "instances"
	// RepositoriesResource / RepositoryCommitsResource are the code provider's
	// plural names (providers/code api/code_repository.go).
	RepositoriesResource      = "repositories"
	RepositoryCommitsResource = "repositorycommits"
)
