apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: providers.railgrid.ai
spec:
  resources:
  - group: providers.railgrid.ai
    name: catalogentries
    schema: v260924-87f1980f.catalogentries.providers.railgrid.ai
    storage:
      crd: {}
status: {}
