/*
Copyright 2026 The Railgrid Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package workspace stores App Studio project files in a provider-owned
// checkout/workspace directory.
package workspace

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"unicode/utf8"

	"github.com/pmezard/go-difflib/difflib"
)

const (
	MaxProjectPathBytes     = 1024
	DefaultListLimit        = 200
	MaxListLimit            = 500
	DefaultReadMaxBytes     = 64 << 10
	MaxReadMaxBytes         = 256 << 10
	MaxWriteBytes           = MaxReadMaxBytes
	MaxFileVersionBytes     = 128
	workspaceTempFilePrefix = ".workspace-write-"
)

// MaxBinaryWriteBytes bounds one binary (non-UTF-8 or NUL-bearing) file. Text
// files keep the MaxWriteBytes cap; binaries such as images, fonts, and 3D
// models are written whole and never returned as model content.
const MaxBinaryWriteBytes = 25 << 20

var errStopWalk = errors.New("stop workspace walk")

// ErrMutationConflict means the workspace changed after the mutation baseline
// was read, so the requested write was not applied.
var ErrMutationConflict = errors.New("workspace file changed during edit")

// Scope identifies one App Studio project workspace incarnation. ProjectUID
// prevents a recreated Project from inheriting the deleted Project's files.
type Scope struct {
	OrgUUID       string
	WorkspaceUUID string
	ProjectName   string
	ProjectUID    string
}

// File is one file to materialize into a project workspace. Content is
// normally UTF-8 text; tree replacement also accepts raw binary bytes (a Go
// string holds arbitrary bytes), bounded by MaxBinaryWriteBytes.
type File struct {
	Path    string
	Content string
}

// FileTooLargeError reports content over the text or binary write bound. The
// REST layer maps it to 413.
type FileTooLargeError struct {
	Path  string
	Size  int64
	Limit int64
	// Binary reports which bound applied.
	Binary bool
}

func (e *FileTooLargeError) Error() string {
	kind := "text"
	if e.Binary {
		kind = "binary"
	}
	return fmt.Sprintf("%s file %q is too large: %d > %d bytes", kind, e.Path, e.Size, e.Limit)
}

// MutationResult describes one workspace mutation.
type MutationResult struct {
	Operation    string   `json:"operation"`
	Changed      bool     `json:"changed"`
	Path         string   `json:"path,omitempty"`
	PreviousPath string   `json:"previousPath,omitempty"`
	Paths        []string `json:"paths,omitempty"`
	Size         int64    `json:"size,omitempty"`
	Version      string   `json:"version,omitempty"`
	Replacements int      `json:"replacements,omitempty"`
	Additions    int      `json:"additions,omitempty"`
	Deletions    int      `json:"deletions,omitempty"`
	// Binary marks a mutation whose content is not UTF-8 text; it carries no
	// line counts or diff. Created distinguishes a new file from a replaced
	// one for whole-file writes (PutFile).
	Binary  bool `json:"binary,omitempty"`
	Created bool `json:"created,omitempty"`
	// Diff is generated by the server from the before/after snapshots. It is
	// never parsed as an assistant command and is bounded by the same result
	// limits as the mutation itself.
	Diff  string           `json:"diff,omitempty"`
	Files []MutationResult `json:"files,omitempty"`
}

// FileInfo describes one file in a project workspace.
type FileInfo struct {
	Path string `json:"path"`
	Size int64  `json:"size,omitempty"`
}

// FileList is a bounded list of files in a project workspace.
type FileList struct {
	Files     []FileInfo `json:"files"`
	Truncated bool       `json:"truncated,omitempty"`
	Limit     int        `json:"limit,omitempty"`
}

// ListOptions configures workspace file listing.
type ListOptions struct {
	Limit int
}

// ReadOptions configures a bounded file read.
type ReadOptions struct {
	Path     string
	MaxBytes int
}

// WriteOptions configures a whole-file workspace write.
type WriteOptions struct {
	Path       string
	Content    string
	CreateOnly bool
}

// CreateOptions configures creation of one new bounded UTF-8 text file.
// Creation is always create-only; existing files are never replaced.
type CreateOptions struct {
	Path    string
	Content string
}

// ReplaceOptions configures an atomic replacement of one existing file. The
// expected version must come from a complete same-turn read of that file.
type ReplaceOptions struct {
	Path            string
	Content         string
	ExpectedVersion string
}

// FileContent is a bounded text-file read response. A binary file never
// returns content; its Version covers the complete file bytes.
type FileContent struct {
	Path    string `json:"path"`
	Content string `json:"content,omitempty"`
	Size    int64  `json:"size"`
	// Version is an opaque content version. It is present only when the read
	// returned the complete bounded file (or the file is binary, whose version
	// is always computed over every byte), so callers can safely use it as the
	// expectedVersion for a subsequent mutation.
	Version   string `json:"version,omitempty"`
	Binary    bool   `json:"binary,omitempty"`
	Truncated bool   `json:"truncated,omitempty"`
}

// fileVersion returns the opaque version used by read-then-mutate contracts.
// The digest is intentionally content-derived rather than a filesystem mtime:
// it remains stable across atomic renames, reloads, and process restarts.
func fileVersion(content []byte) string {
	sum := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// FileStore stores workspaces under a root directory.
type FileStore struct {
	root       string
	mutationMu sync.Mutex
	// managedTransactionHook is a package-test seam. It is called immediately
	// before each staged managed-file change is committed, while mutationMu is
	// held, so tests can deterministically exercise rollback after a later
	// operation fails. Production callers leave it nil.
	managedTransactionHook func(ManagedFileChange) error
	// migrationMu serializes the one-time compatibility transition from the
	// pre-ProjectUID layout. It is intentionally separate from mutationMu so
	// path resolution can safely migrate data before a caller takes the
	// workspace mutation lock.
	migrationMu sync.Mutex
	// ledger is the process-wide default working-copy ledger (see ledger.go).
	// Production leaves it nil and attaches a caller- or reconciler-scoped
	// ledger to each call's context instead; tests and REST-only local runs
	// set an in-memory one.
	ledger Ledger
}

// NewFileStore returns a filesystem-backed project workspace store with an
// IN-PROCESS working-copy ledger.
//
// That default is for tests and for a local run with no control plane to talk
// to. A deployment calls RequireContextLedger immediately afterwards, which
// removes it: from then on every ledger operation must carry a
// control-plane-backed ledger on its context (workspace/ledger.go), and a call
// path that forgot to attach one fails loudly instead of quietly writing
// authority into this process's memory.
func NewFileStore(root string) *FileStore {
	return &FileStore{
		root:   strings.TrimSpace(root),
		ledger: NewMemoryLedger(),
	}
}

// RequireContextLedger drops the in-process default ledger, so the working-copy
// ledger must come from the call's context. It is what makes "the ledger is not
// pod-local" checkable rather than merely intended.
func (s *FileStore) RequireContextLedger() {
	if s == nil {
		return
	}
	s.ledger = nil
}

// CleanProjectPath returns the canonical workspace-relative path accepted by
// FileStore APIs.
func CleanProjectPath(raw string) (string, error) {
	return cleanProjectPath(raw)
}

// Root returns the filesystem root used by the store.
func (s *FileStore) Root() string {
	return s.root
}

// ApplyFiles writes a batch of files into the scoped project workspace.
func (s *FileStore) ApplyFiles(ctx context.Context, scope Scope, files []File) error {
	if s == nil {
		return errors.New("project workspace store is not configured")
	}
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()
	return s.applyFiles(ctx, scope, files)
}

func (s *FileStore) applyFiles(ctx context.Context, scope Scope, files []File) error {
	dir, err := s.scopeDir(scope)
	if err != nil {
		return err
	}
	planned := make([]File, 0, len(files))
	for _, f := range files {
		if err := ctx.Err(); err != nil {
			return err
		}
		clean, err := cleanProjectPath(f.Path)
		if err != nil {
			return err
		}
		target := filepath.Join(dir, filepath.FromSlash(clean))
		if err := ensureWithin(dir, target); err != nil {
			return err
		}
		if err := mkdirAllForFile(dir, clean); err != nil {
			return fmt.Errorf("create parent directory for %q: %w", clean, err)
		}
		if err := rejectSymlink(target, clean); err != nil {
			return err
		}
		before, existed, err := s.readMutationTarget(ctx, scope, clean)
		if err != nil {
			return err
		}
		if existed && bytes.Equal(before, []byte(f.Content)) {
			continue
		}
		planned = append(planned, File{Path: clean, Content: f.Content})
	}
	if len(planned) == 0 {
		return nil
	}
	// Advance the durable authority before writing bytes. If a later write
	// fails (or the process stops mid-batch), the revision gap is safe: the
	// next sync/exec must reconcile the current live workspace rather than
	// trusting a stale revision.
	if err := s.bumpSourceRevision(ctx, scope); err != nil {
		return err
	}
	for _, f := range planned {
		if err := ctx.Err(); err != nil {
			return err
		}
		clean := f.Path
		target := filepath.Join(dir, filepath.FromSlash(clean))
		if err := ensureWithin(dir, target); err != nil {
			return err
		}
		if err := mkdirAllForFile(dir, clean); err != nil {
			return fmt.Errorf("create parent directory for %q: %w", clean, err)
		}
		if err := rejectSymlink(target, clean); err != nil {
			return err
		}
		if err := writeFileAtomically(filepath.Dir(target), target, []byte(f.Content), 0o644, false); err != nil {
			return fmt.Errorf("write %q: %w", clean, err)
		}
	}
	return nil
}

// WriteFile is the provider's legacy hydration primitive. Assistant-facing
// mutations must use CreateFile or ReplaceFile; this method remains for
// snapshot/bootstrap paths that intentionally reconcile whole files.
func (s *FileStore) WriteFile(ctx context.Context, scope Scope, opts WriteOptions) (MutationResult, error) {
	if s == nil {
		return MutationResult{}, errors.New("project workspace store is not configured")
	}
	if err := validateMutationContent(opts.Path, opts.Content); err != nil {
		return MutationResult{}, err
	}
	s.mutationMu.Lock()
	defer s.mutationMu.Unlock()

	clean, _ := cleanProjectPath(opts.Path)
	before, existed, err := s.readMutationTarget(ctx, scope, clean)
	if err != nil {
		return MutationResult{}, err
	}
	if opts.CreateOnly && existed {
		return MutationResult{}, newMutationError(MutationErrorTargetExists, clean, "target already exists")
	}
	if existed && bytes.Equal(before, []byte(opts.Content)) {
		result := mutationResult("write_file", clean, before, opts.Content, 0)
		result.Changed = false
		return result, nil
	}
	if err := s.writeMutationLocked(ctx, scope, clean, []byte(opts.Content), opts.CreateOnly); err != nil {
		return MutationResult{}, err
	}
	return mutationResult("write_file", clean, before, opts.Content, 0), nil
}

func writeFileAtomically(dir, target string, content []byte, mode fs.FileMode, createOnly bool) error {
	if !createOnly {
		info, err := os.Lstat(target)
		switch {
		case err == nil:
			mode = info.Mode().Perm()
		case !errors.Is(err, fs.ErrNotExist):
			return err
		}
	}
	file, err := os.CreateTemp(dir, workspaceTempFilePrefix+"*")
	if err != nil {
		return err
	}
	temp := file.Name()
	defer func() { _ = os.Remove(temp) }()
	if err := file.Chmod(mode); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(content); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	if createOnly {
		return os.Link(temp, target)
	}
	return os.Rename(temp, target)
}

func mutationResult(operation, filePath string, before []byte, after string, replacements int) MutationResult {
	beforeLines := difflib.SplitLines(string(before))
	afterLines := difflib.SplitLines(after)
	additions, deletions := 0, 0
	for _, op := range difflib.NewMatcher(beforeLines, afterLines).GetOpCodes() {
		switch op.Tag {
		case 'i':
			additions += op.J2 - op.J1
		case 'd':
			deletions += op.I2 - op.I1
		case 'r':
			additions += op.J2 - op.J1
			deletions += op.I2 - op.I1
		}
	}
	patch, _ := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
		A:        beforeLines,
		B:        afterLines,
		FromFile: "a/" + filePath,
		ToFile:   "b/" + filePath,
		Context:  3,
	})
	version := fileVersion([]byte(after))
	if operation == "delete_file" {
		version = ""
	}
	return MutationResult{
		Operation:    operation,
		Changed:      true,
		Path:         filePath,
		Size:         int64(len([]byte(after))),
		Version:      version,
		Replacements: replacements,
		Additions:    additions,
		Deletions:    deletions,
		Diff:         patch,
	}
}

// ListFiles lists regular files in the scoped project workspace.
func (s *FileStore) ListFiles(ctx context.Context, scope Scope, opts ListOptions) (FileList, error) {
	dir, err := s.scopeDir(scope)
	if err != nil {
		return FileList{}, err
	}
	limit := boundedPositive(opts.Limit, DefaultListLimit, MaxListLimit)
	files, err := s.allFiles(ctx, dir, limit+1)
	if err != nil {
		return FileList{}, err
	}
	truncated := len(files) > limit
	if truncated {
		files = files[:limit]
	}
	return FileList{Files: files, Truncated: truncated, Limit: limit}, nil
}

// ReadFile reads a bounded file from the scoped project workspace. Text
// beyond MaxBytes is truncated (no version). A binary file is detected from
// its bytes, never returns content, and always carries a version computed by
// streaming the whole file, so it can be deleted, moved, or replaced safely.
func (s *FileStore) ReadFile(ctx context.Context, scope Scope, opts ReadOptions) (FileContent, error) {
	clean, f, info, err := s.openRegularFile(ctx, scope, opts.Path)
	if err != nil {
		return FileContent{}, err
	}
	defer func() { _ = f.Close() }()
	maxBytes := boundedPositive(opts.MaxBytes, DefaultReadMaxBytes, MaxReadMaxBytes)
	buf, err := io.ReadAll(io.LimitReader(f, int64(maxBytes)+1))
	if err != nil {
		return FileContent{}, fmt.Errorf("read %q: %w", clean, err)
	}
	truncated := len(buf) > maxBytes
	if truncated {
		buf = buf[:maxBytes]
	}
	// Classify on the raw bytes: trimming first would turn a binary prefix
	// into an empty "text" read.
	if (truncated && !textPrefix(buf)) || (!truncated && isBinary(buf)) {
		version, err := streamFileVersion(ctx, f)
		if err != nil {
			return FileContent{}, fmt.Errorf("read %q: %w", clean, err)
		}
		return FileContent{Path: clean, Size: info.Size(), Binary: true, Version: version}, nil
	}
	if truncated {
		buf = trimValidUTF8(buf)
	}
	result := FileContent{Path: clean, Content: string(buf), Size: info.Size(), Truncated: truncated}
	if !truncated {
		result.Version = fileVersion(buf)
	}
	return result, nil
}

// ReadFileBytes returns the complete bytes of one file of either kind, for
// callers that ship whole files (repository commits, development sync). A
// file larger than limit returns *FileTooLargeError without reading it; a
// missing file wraps fs.ErrNotExist.
func (s *FileStore) ReadFileBytes(ctx context.Context, scope Scope, rawPath string, limit int64) ([]byte, error) {
	clean, f, info, err := s.openRegularFile(ctx, scope, rawPath)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	if limit > 0 && info.Size() > limit {
		return nil, &FileTooLargeError{Path: clean, Size: info.Size(), Limit: limit, Binary: true}
	}
	var reader io.Reader = contextReader{ctx: ctx, r: f}
	if limit > 0 {
		reader = io.LimitReader(reader, limit+1)
	}
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", clean, err)
	}
	if limit > 0 && int64(len(data)) > limit {
		return nil, &FileTooLargeError{Path: clean, Size: int64(len(data)), Limit: limit, Binary: true}
	}
	return data, nil
}

// OpenFile opens one regular workspace file for streaming (raw downloads).
// The caller must close the returned file. A missing file wraps
// fs.ErrNotExist.
func (s *FileStore) OpenFile(ctx context.Context, scope Scope, rawPath string) (*os.File, fs.FileInfo, error) {
	_, f, info, err := s.openRegularFile(ctx, scope, rawPath)
	return f, info, err
}

// openRegularFile resolves and opens one regular file without following
// symlinks anywhere on its path.
func (s *FileStore) openRegularFile(ctx context.Context, scope Scope, rawPath string) (string, *os.File, fs.FileInfo, error) {
	dir, err := s.scopeDir(scope)
	if err != nil {
		return "", nil, nil, err
	}
	clean, err := cleanProjectPath(rawPath)
	if err != nil {
		return "", nil, nil, err
	}
	target := filepath.Join(dir, filepath.FromSlash(clean))
	if err := ensureWithin(dir, target); err != nil {
		return "", nil, nil, err
	}
	if err := rejectSymlinkComponents(dir, clean, true); err != nil {
		return "", nil, nil, err
	}
	info, err := os.Lstat(target)
	if err != nil {
		return "", nil, nil, fmt.Errorf("read %q: %w", clean, err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return "", nil, nil, fmt.Errorf("read %q: symlink paths are not allowed", clean)
	}
	if info.IsDir() {
		return "", nil, nil, fmt.Errorf("%q is a directory", clean)
	}
	if !info.Mode().IsRegular() {
		return "", nil, nil, fmt.Errorf("path %q is not a regular file", clean)
	}
	if err := ctx.Err(); err != nil {
		return "", nil, nil, err
	}
	f, err := os.Open(target)
	if err != nil {
		return "", nil, nil, fmt.Errorf("open %q: %w", clean, err)
	}
	return clean, f, info, nil
}

// streamFileVersion hashes every byte of f from the start.
func streamFileVersion(ctx context.Context, f *os.File) (string, error) {
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		return "", err
	}
	hash := sha256.New()
	if _, err := io.Copy(hash, contextReader{ctx: ctx, r: f}); err != nil {
		return "", err
	}
	return "sha256:" + hex.EncodeToString(hash.Sum(nil)), nil
}

// contextReader stops a long streaming read once ctx is done.
type contextReader struct {
	ctx context.Context
	r   io.Reader
}

func (c contextReader) Read(p []byte) (int, error) {
	if err := c.ctx.Err(); err != nil {
		return 0, err
	}
	return c.r.Read(p)
}

func (s *FileStore) allFiles(ctx context.Context, dir string, maxFiles int) ([]FileInfo, error) {
	files := []FileInfo{}
	err := s.walkFiles(ctx, dir, func(file FileInfo) error {
		files = append(files, file)
		if maxFiles > 0 && len(files) >= maxFiles {
			return errStopWalk
		}
		return nil
	})
	if err != nil && !errors.Is(err, errStopWalk) {
		return nil, err
	}
	sort.Slice(files, func(i, j int) bool {
		return files[i].Path < files[j].Path
	})
	return files, nil
}

func (s *FileStore) walkFiles(ctx context.Context, dir string, visit func(FileInfo) error) error {
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("stat workspace: %w", err)
	}
	err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		name := d.Name()
		if d.IsDir() && (name == ".git" || name == "node_modules" || strings.EqualFold(name, workspaceSnapshotDirectory) || strings.HasPrefix(name, workspaceTempFilePrefix)) {
			return filepath.SkipDir
		}
		if !d.IsDir() && strings.HasPrefix(name, workspaceTempFilePrefix) {
			return nil
		}
		if d.IsDir() {
			return nil
		}
		if !d.Type().IsRegular() {
			return nil
		}
		rel, err := filepath.Rel(dir, p)
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		return visit(FileInfo{Path: filepath.ToSlash(rel), Size: info.Size()})
	})
	if err != nil {
		return fmt.Errorf("list workspace files: %w", err)
	}
	return nil
}

func (s *FileStore) scopeDir(scope Scope) (string, error) {
	if s == nil || strings.TrimSpace(s.root) == "" {
		return "", errors.New("project workspace store is not configured")
	}
	parts := []string{scope.OrgUUID, scope.WorkspaceUUID, scope.ProjectName, scope.ProjectUID}
	for _, part := range parts {
		if err := validateScopeSegment(part); err != nil {
			return "", err
		}
	}
	if err := s.migrateLegacyWorkspace(scope); err != nil {
		return "", err
	}
	return filepath.Join(s.root, scope.OrgUUID, scope.WorkspaceUUID, scope.ProjectName, scope.ProjectUID), nil
}

func validateScopeSegment(value string) error {
	value = strings.TrimSpace(value)
	if value == "" {
		return errors.New("workspace scope is incomplete")
	}
	if strings.ContainsAny(value, `/\`+"\x00") || value == "." || value == ".." {
		return fmt.Errorf("invalid workspace scope segment %q", value)
	}
	return nil
}

func cleanProjectPath(raw string) (string, error) {
	raw = strings.TrimSpace(strings.ReplaceAll(raw, "\\", "/"))
	if raw == "" {
		return "", errors.New("file path cannot be empty")
	}
	if len([]byte(raw)) > MaxProjectPathBytes {
		return "", fmt.Errorf("file path %q is too long", raw)
	}
	if strings.HasPrefix(raw, "/") || path.IsAbs(raw) {
		return "", fmt.Errorf("file path %q must be relative", raw)
	}
	for _, part := range strings.Split(raw, "/") {
		if part == ".." {
			return "", fmt.Errorf("file path %q cannot contain a %q segment", raw, "..")
		}
		if isReservedPathSegment(part) {
			return "", fmt.Errorf("file path %q contains reserved segment %q", raw, part)
		}
		if strings.ContainsRune(part, '\x00') {
			return "", fmt.Errorf("file path %q cannot contain NUL", raw)
		}
	}
	clean := path.Clean(raw)
	if clean == "." || clean == "" {
		return "", errors.New("file path cannot be empty")
	}
	return clean, nil
}

func ensureWithin(root, target string) error {
	rel, err := filepath.Rel(root, target)
	if err != nil {
		return err
	}
	if rel == "." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || rel == ".." {
		return fmt.Errorf("path %q escapes workspace", target)
	}
	return nil
}

func isReservedPathSegment(part string) bool {
	part = strings.ToLower(strings.TrimSpace(part))
	if strings.HasPrefix(part, workspaceTempFilePrefix) {
		return true
	}
	switch part {
	case ".git", "node_modules", workspaceSnapshotDirectory:
		return true
	default:
		return false
	}
}

func mkdirAllForFile(root, clean string) error {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return err
	}
	parent := path.Dir(clean)
	if parent == "." {
		return nil
	}
	current := root
	seen := []string{}
	for _, part := range strings.Split(parent, "/") {
		if part == "" || part == "." {
			continue
		}
		seen = append(seen, part)
		relPath := strings.Join(seen, "/")
		next := filepath.Join(current, filepath.FromSlash(part))
		info, err := os.Lstat(next)
		if err == nil {
			if info.Mode()&os.ModeSymlink != 0 {
				return fmt.Errorf("path %q contains a symlink", relPath)
			}
			if !info.IsDir() {
				return fmt.Errorf("path %q is not a directory", relPath)
			}
			current = next
			continue
		}
		if !os.IsNotExist(err) {
			return err
		}
		if err := os.Mkdir(next, 0o755); err != nil && !os.IsExist(err) {
			return err
		}
		current = next
	}
	return nil
}

func rejectSymlinkComponents(root, clean string, includeTarget bool) error {
	current := root
	parts := strings.Split(clean, "/")
	for i, part := range parts {
		if part == "" || part == "." {
			continue
		}
		current = filepath.Join(current, filepath.FromSlash(part))
		info, err := os.Lstat(current)
		if os.IsNotExist(err) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("stat %q: %w", strings.Join(parts[:i+1], "/"), err)
		}
		if !includeTarget && i == len(parts)-1 {
			return nil
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("path %q contains a symlink", strings.Join(parts[:i+1], "/"))
		}
		if !info.IsDir() && i < len(parts)-1 {
			return fmt.Errorf("path %q is not a directory", strings.Join(parts[:i+1], "/"))
		}
	}
	return nil
}

func rejectSymlink(target, clean string) error {
	info, err := os.Lstat(target)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("stat %q: %w", clean, err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("path %q is a symlink", clean)
	}
	return nil
}

func validateMutationContent(path, content string) error {
	if _, err := cleanProjectPath(path); err != nil {
		return err
	}
	if len([]byte(content)) > MaxWriteBytes {
		return fmt.Errorf("file %q is too large: %d > %d bytes", path, len([]byte(content)), MaxWriteBytes)
	}
	if !validTextContent(content) {
		return fmt.Errorf("file %q must be UTF-8 text without NUL bytes", path)
	}
	return nil
}

func validTextContent(content string) bool {
	return utf8.ValidString(content) && !strings.ContainsRune(content, '\x00')
}

func boundedPositive(value, fallback, maximum int) int {
	if value > maximum {
		return maximum
	}
	if value > 0 {
		return value
	}
	return fallback
}

func trimValidUTF8(buf []byte) []byte {
	for len(buf) > 0 && !utf8.Valid(buf) {
		buf = buf[:len(buf)-1]
	}
	return buf
}

func isBinary(buf []byte) bool {
	return bytes.IndexByte(buf, 0) >= 0 || !utf8.Valid(buf)
}

// IsBinaryContent reports whether content is binary under the workspace
// contract: anything that is not UTF-8 text without NUL bytes.
func IsBinaryContent(content []byte) bool {
	return isBinary(content)
}

// textPrefix reports whether buf, a bounded prefix of a longer file, is
// UTF-8 text without NUL bytes. A rune cut by the read bound is tolerated.
func textPrefix(buf []byte) bool {
	if bytes.IndexByte(buf, 0) >= 0 {
		return false
	}
	if utf8.Valid(buf) {
		return true
	}
	for i := len(buf) - 1; i >= 0 && i >= len(buf)-utf8.UTFMax; i-- {
		if utf8.RuneStart(buf[i]) {
			return !utf8.FullRune(buf[i:]) && utf8.Valid(buf[:i])
		}
	}
	return false
}

// ValidateFileBytes applies the per-file write bound for content of either
// kind: MaxWriteBytes for text, MaxBinaryWriteBytes for binary. An over-bound
// file returns *FileTooLargeError.
func ValidateFileBytes(path string, content []byte) error {
	return validateFileBytes(path, content)
}

func validateFileBytes(path string, content []byte) error {
	if _, err := cleanProjectPath(path); err != nil {
		return err
	}
	if isBinary(content) {
		if len(content) > MaxBinaryWriteBytes {
			return &FileTooLargeError{Path: path, Size: int64(len(content)), Limit: MaxBinaryWriteBytes, Binary: true}
		}
		return nil
	}
	if len(content) > MaxWriteBytes {
		return &FileTooLargeError{Path: path, Size: int64(len(content)), Limit: MaxWriteBytes}
	}
	return nil
}

// textDetector classifies a stream as text or binary without buffering it.
// It carries at most one incomplete rune between writes.
type textDetector struct {
	carry  []byte
	binary bool
}

func (d *textDetector) Write(p []byte) (int, error) {
	if d.binary {
		return len(p), nil
	}
	if bytes.IndexByte(p, 0) >= 0 {
		d.binary = true
		return len(p), nil
	}
	buf := append(append([]byte(nil), d.carry...), p...)
	cut := len(buf)
	for i := len(buf) - 1; i >= 0 && i >= len(buf)-utf8.UTFMax; i-- {
		if utf8.RuneStart(buf[i]) {
			if !utf8.FullRune(buf[i:]) {
				cut = i
			}
			break
		}
	}
	if !utf8.Valid(buf[:cut]) {
		d.binary = true
		return len(p), nil
	}
	d.carry = append(d.carry[:0], buf[cut:]...)
	return len(p), nil
}

// Text reports whether everything written so far is complete UTF-8 text.
func (d *textDetector) Text() bool {
	return !d.binary && len(d.carry) == 0
}
